// Interoperability tests against the python-omemo reference stack
// (xeddsa / x3dh / doubleratchet / oldmemo / twomemo). Test vectors are
// generated by scripts/gen_vectors.py into vectors.json. A subset of tests
// call scripts/py_verify.py to let the reference stack verify or decrypt
// output produced by this implementation; those tests are skipped when the
// venv is not available.

import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { x25519 } from '@noble/curves/ed25519.js'

import {
  aes128GcmDecrypt,
  aes128GcmEncrypt,
  aes256CbcDecrypt,
  aes256CbcEncrypt
} from '../../src/crypto/aes'
import { hkdfSha256 } from '../../src/crypto/kdf'
import {
  curvePublicToEdPublic,
  curveSecretSignBit,
  decodeCurveKeyWire,
  edPublicToCurvePublic,
  edSecretToCurveSecret,
  encodeCurveKeyWire,
  x25519SharedSecret
} from '../../src/crypto/keys'
import { xed25519Sign, xed25519Verify } from '../../src/crypto/xed25519'
import { bytesToHex, hexToBytes } from '../../src/internal/bytes'
import { parseXml } from '../../src/internal/xml'
import {
  decodeAuthenticatedMessage,
  decodeKeyExchange,
  decodeOmemoMessage,
  encodeAuthenticatedMessage,
  encodeKeyExchange,
  encodeOmemoMessage
} from '../../src/protocol/messages'
import { PROFILES } from '../../src/protocol/profiles'
import { Session } from '../../src/protocol/session'
import type { SessionState } from '../../src/protocol/session'
import { sessionResponder } from '../../src/protocol/sessionInit'
import { x3dhInitiate, x3dhRespond } from '../../src/protocol/x3dh'
import type { ParsedBundle } from '../../src/protocol/bundle'
import { parseBundle } from '../../src/protocol/bundle'
import {
  decodeKeyExchangeWire,
  encodeKeyExchangeWire
} from '../../src/protocol/keyExchange'
import { parseEncryptedElement } from '../../src/protocol/wire'
import type { Namespace } from '../../src/constants'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const PKG = path.resolve(HERE, '..', '..')
const PYTHON = path.join(PKG, '.venv', 'bin', 'python')
const BRIDGE = path.join(PKG, 'scripts', 'py_verify.py')
const HAS_PYTHON = existsSync(PYTHON)

const vectors = JSON.parse(readFileSync(path.join(HERE, 'vectors.json'), 'utf8'))

function hex(s: string): Uint8Array {
  return hexToBytes(s)
}

function expectBytes(actual: Uint8Array, expectedHex: string): void {
  expect(bytesToHex(actual)).toBe(expectedHex)
}

interface PyResult {
  ok: boolean
  error?: string
  [key: string]: unknown
}

function py(request: Record<string, unknown>): PyResult {
  const out = execFileSync(PYTHON, [BRIDGE], {
    input: JSON.stringify(request),
    timeout: 30000
  })
  return JSON.parse(out.toString('utf8')) as PyResult
}

// Map a reference DoubleRatchetModel dump (as emitted by gen_vectors.py) to
// our SessionState. own ratchet public key is rederived from the private key.
function sessionStateFromModel(
  model: Record<string, unknown>,
  initiation: 'active' | 'passive',
  ad: Uint8Array,
  localIdentity: Uint8Array,
  remoteIdentity: Uint8Array
): SessionState {
  const m = model as {
    ownRatchetPriv: string
    otherRatchetPub: string
    rootChain: { length: number; key: string } | null
    sendingChain: { length: number; key: string } | null
    receivingChain: { length: number; key: string } | null
    previousSendingChainLength: number | null
    skippedMessageKeys: { ratchetPub: string; index: number; messageKey: string }[]
  }
  const dhsPriv = hex(m.ownRatchetPriv)
  return {
    initiation,
    rk: hex(m.rootChain?.key ?? ''),
    cks: m.sendingChain === null ? null : hex(m.sendingChain.key),
    ckr: m.receivingChain === null ? null : hex(m.receivingChain.key),
    dhs: { privateKey: dhsPriv, publicKey: x25519.getPublicKey(dhsPriv) },
    dhr: m.otherRatchetPub === '' ? null : hex(m.otherRatchetPub),
    ns: m.sendingChain?.length ?? 0,
    nr: m.receivingChain?.length ?? 0,
    pn: m.previousSendingChainLength ?? 0,
    ad,
    remoteIdentity,
    localIdentity,
    pendingKeyExchange: null,
    skipped: m.skippedMessageKeys.map((k) => ({
      dh: hex(k.ratchetPub),
      n: k.index,
      mk: hex(k.messageKey)
    })),
    confirmed: false
  }
}

function wireIdentity(ns: Namespace, identity: { curvePub: string; edPub: string }): Uint8Array {
  return ns === 'legacy'
    ? encodeCurveKeyWire(hex(identity.curvePub))
    : hex(identity.edPub)
}

// --------------------------------------------------------------------------
// symmetric primitives
// --------------------------------------------------------------------------

describe('HKDF-SHA256 (RFC 5869)', () => {
  for (const [i, c] of vectors.hkdf.cases.entries()) {
    it(`test case ${i + 1}`, () => {
      const okm = hkdfSha256(hex(c.ikm), hex(c.salt), hex(c.info), c.length)
      expectBytes(okm, c.okm)
      // undefined salt must behave like a 32 byte zero salt
      const zeroSalt = new Uint8Array(32)
      const okm2 = hkdfSha256(hex(c.ikm), undefined, hex(c.info), c.length)
      const okm3 = hkdfSha256(hex(c.ikm), zeroSalt, hex(c.info), c.length)
      expect(bytesToHex(okm2)).toBe(bytesToHex(okm3))
    })
  }
})

describe('AES vectors', () => {
  for (const [i, c] of vectors.aes.cbc.entries()) {
    it(`AES-256-CBC vector ${i + 1}`, () => {
      expectBytes(aes256CbcEncrypt(hex(c.key), hex(c.iv), hex(c.plaintext)), c.ciphertext)
      expectBytes(aes256CbcDecrypt(hex(c.key), hex(c.iv), hex(c.ciphertext)), c.plaintext)
    })
  }
  for (const [i, c] of vectors.aes.gcm.entries()) {
    it(`AES-128-GCM vector ${i + 1}`, () => {
      const res = aes128GcmEncrypt(hex(c.key), hex(c.iv), hex(c.plaintext))
      expectBytes(res.ciphertext, c.ciphertext)
      expectBytes(res.tag, c.tag)
      expectBytes(
        aes128GcmDecrypt(hex(c.key), hex(c.iv), hex(c.ciphertext), hex(c.tag)),
        c.plaintext
      )
    })
  }
})

// --------------------------------------------------------------------------
// XEdDSA and key conversion
// --------------------------------------------------------------------------

describe('XEdDSA (python-xeddsa vectors)', () => {
  const msg = hex(vectors.xeddsa.message)

  for (const [i, c] of vectors.xeddsa.cases.entries()) {
    it(`vector ${i + 1}: reference signature verifies under our rules`, () => {
      const res = xed25519Verify(encodeCurveKeyWire(hex(c.curvePub)), msg, hex(c.signature))
      expect(res.valid).toBe(true)
      expectBytes(res.ed25519PublicKey, c.edPub)
    })

    it(`vector ${i + 1}: sign bit matches`, () => {
      expect(curveSecretSignBit(hex(c.priv))).toBe(c.signBit)
      // the smuggled bit in the reference signature is the same bit
      expect((hex(c.signature)[63] ?? 0) >> 7).toBe(c.signBit)
    })

    it(`vector ${i + 1}: our signature verifies and carries the sign bit`, () => {
      const sig = xed25519Sign(hex(c.priv), msg)
      expect((sig[63] ?? 0) >> 7).toBe(c.signBit)
      const res = xed25519Verify(encodeCurveKeyWire(hex(c.curvePub)), msg, sig)
      expect(res.valid).toBe(true)
      expectBytes(res.ed25519PublicKey, c.edPub)
      const flipped = Uint8Array.from(sig)
      flipped[10] = (flipped[10] ?? 0) ^ 1
      expect(
        xed25519Verify(encodeCurveKeyWire(hex(c.curvePub)), msg, flipped).valid
      ).toBe(false)
    })

    it.skipIf(!HAS_PYTHON)(`vector ${i + 1}: our signature verifies under xeddsa`, () => {
      const sig = xed25519Sign(hex(c.priv), msg)
      const res = py({
        op: 'xeddsa_verify_curve',
        curvePub: c.curvePub,
        signBit: c.signBit,
        msg: vectors.xeddsa.message,
        sig: bytesToHex(sig)
      })
      expect(res.ok).toBe(true)
      expect(res.valid).toBe(true)
    })
  }
})

describe('Ed25519 <-> Curve25519 conversion', () => {
  for (const [i, c] of vectors.edCurve.cases.entries()) {
    it(`vector ${i + 1}`, () => {
      expectBytes(edSecretToCurveSecret(hex(c.seed)), c.curvePriv)
      expectBytes(edPublicToCurvePublic(hex(c.edPub)), c.curvePub)
      expectBytes(curvePublicToEdPublic(hex(c.curvePub), 0), c.edFromCurveSign0)
      expectBytes(curvePublicToEdPublic(hex(c.curvePub), 1), c.edFromCurveSign1)
      expectBytes(encodeCurveKeyWire(hex(c.curvePub)), c.wire)
      expectBytes(decodeCurveKeyWire(hex(c.wire)), c.curvePub)
      expectBytes(decodeCurveKeyWire(hex(c.curvePub)), c.curvePub)
    })
  }
})

describe('X25519 shared secrets', () => {
  for (const [i, c] of vectors.x25519.cases.entries()) {
    it(`vector ${i + 1}`, () => {
      expectBytes(x25519SharedSecret(hex(c.priv), hex(c.pub)), c.shared)
    })
  }
})

// --------------------------------------------------------------------------
// X3DH
// --------------------------------------------------------------------------

describe('X3DH key agreement', () => {
  for (const ns of ['omemo2', 'legacy'] as const) {
    const v = vectors.x3dh[ns]

    it(`${ns}: passive side reproduces reference shared secret and AD`, () => {
      const profile = PROFILES[ns]
      const own =
        ns === 'legacy'
          ? {
              privateKey: hex(v.identityB.priv),
              publicKey: hex(v.identityB.curvePub),
              wirePublicKey: encodeCurveKeyWire(hex(v.identityB.curvePub))
            }
          : {
              privateKey: hex(v.identityB.seed),
              publicKey: hex(v.identityB.edPub),
              wirePublicKey: hex(v.identityB.edPub)
            }
      const res = x3dhRespond(profile, own, {
        ik: wireIdentity(ns, v.identityA),
        ek: hex(v.ephemeral.pub),
        spkId: v.signedPreKey.id,
        pkId: v.preKey.id,
        signedPreKey: {
          privateKey: hex(v.signedPreKey.priv),
          publicKey: hex(v.signedPreKey.pub)
        },
        preKey: { privateKey: hex(v.preKey.priv), publicKey: hex(v.preKey.pub) }
      })
      expectBytes(res.sharedSecret, v.sharedSecret)
      expectBytes(res.associatedData, v.associatedData)
    })

    it.skipIf(!HAS_PYTHON)(
      `${ns}: our active side produces a secret the reference passive side derives`,
      () => {
        const profile = PROFILES[ns]
        const bundle: ParsedBundle = {
          namespace: ns,
          identityKeyWire: wireIdentity(ns, v.identityB),
          identityKeyCurve: hex(v.identityB.curvePub),
          identityKeyEd: hex(v.identityB.edPub),
          signedPreKeyId: v.signedPreKey.id,
          signedPreKey: hex(v.signedPreKey.pub),
          signedPreKeySignature: hex(v.signedPreKey.sig),
          preKeys: [{ pkId: v.preKey.id, pk: hex(v.preKey.pub) }]
        }
        const own =
          ns === 'legacy'
            ? {
                privateKey: hex(v.identityA.priv),
                publicKey: hex(v.identityA.curvePub),
                wirePublicKey: encodeCurveKeyWire(hex(v.identityA.curvePub))
              }
            : {
                privateKey: hex(v.identityA.seed),
                publicKey: hex(v.identityA.edPub),
                wirePublicKey: hex(v.identityA.edPub)
              }
        const res = x3dhInitiate(profile, own, bundle, { random: () => 0 })
        const pyRes = py({
          op: 'x3dh_passive',
          profile: ns,
          ikPriv: v.identityB.priv,
          spkPriv: v.signedPreKey.priv,
          pkPriv: v.preKey.priv,
          header: {
            ikEdPub: v.identityA.edPub,
            ek: bytesToHex(res.ephemeral.publicKey),
            spkPub: v.signedPreKey.pub,
            pkPub: v.preKey.pub
          }
        })
        expect(pyRes.ok).toBe(true)
        expect(bytesToHex(res.sharedSecret)).toBe(pyRes.sharedSecret)
        expect(bytesToHex(res.associatedData)).toBe(pyRes.associatedData)
        expect(res.preKeyId).toBe(v.preKey.id)
        expect(res.signedPreKeyId).toBe(v.signedPreKey.id)
      }
    )
  }
})

// --------------------------------------------------------------------------
// Double ratchet
// --------------------------------------------------------------------------

describe('double ratchet session (python encrypt -> our decrypt)', () => {
  for (const ns of ['omemo2', 'legacy'] as const) {
    const profile = PROFILES[ns]
    const x3dh = vectors.x3dh[ns]
    const dr = vectors.ratchet[ns]
    const ad = hex(x3dh.associatedData)
    const ikA = wireIdentity(ns, x3dh.identityA)
    const ikB = wireIdentity(ns, x3dh.identityB)

    function responderSession(): Session {
      return sessionResponder(profile, {
        sharedSecret: hex(x3dh.sharedSecret),
        associatedData: ad,
        ownRatchet: {
          privateKey: hex(x3dh.signedPreKey.priv),
          publicKey: hex(x3dh.signedPreKey.pub)
        },
        localIdentity: ikB,
        remoteIdentity: ikA
      })
    }

    it(`${ns}: responder decrypts the reference initiator messages in order`, () => {
      const session = responderSession()
      for (const m of dr.aliceToBob) {
        expectBytes(session.decrypt(hex(m.wire.ciphertext)), m.plaintext)
      }
    })

    it(`${ns}: responder handles out-of-order delivery`, () => {
      const session = responderSession()
      const [m1, m2, m3] = dr.aliceToBob
      expectBytes(session.decrypt(hex(m1.wire.ciphertext)), m1.plaintext)
      expectBytes(session.decrypt(hex(m3.wire.ciphertext)), m3.plaintext)
      // after skipping index 1 the skipped store must hold the reference key
      const skipped = session.state.skipped
      const refSkipped = dr.bobModelOutOfOrder.skippedMessageKeys
      expect(skipped.length).toBe(refSkipped.length)
      for (const [i, ref] of refSkipped.entries()) {
        const entry = skipped[i]
        expect(entry).toBeDefined()
        expectBytes(entry!.dh, ref.ratchetPub)
        expect(entry!.n).toBe(ref.index)
        expectBytes(entry!.mk, ref.messageKey)
      }
      expectBytes(session.decrypt(hex(m2.wire.ciphertext)), m2.plaintext)
    })

    it(`${ns}: initiator-side session decrypts the reference reply`, () => {
      const state = sessionStateFromModel(dr.aliceModelAfterSend3, 'active', ad, ikA, ikB)
      const session = new Session(profile, state)
      expectBytes(session.decrypt(hex(dr.bobReply.wire.ciphertext)), dr.bobReply.plaintext)
    })

    it.skipIf(!HAS_PYTHON)(
      `${ns}: our initiator-side encryption decrypts on the reference side`,
      () => {
        const state = sessionStateFromModel(dr.aliceModelAfterSend3, 'active', ad, ikA, ikB)
        const session = new Session(profile, state)
        const plaintext = new Uint8Array([1, 2, 3, 4, 5, 42])
        const encrypted = session.encrypt(plaintext)
        const res = py({
          op: 'dr_decrypt',
          profile: ns,
          model: dr.bobModelFinal,
          ad: x3dh.associatedData,
          wire: {
            ratchetPub: dr.aliceRatchet.pub,
            pn: 0,
            n: 3,
            ciphertext: bytesToHex(encrypted.wire)
          }
        })
        expect(res.ok).toBe(true)
        expect(res.plaintext).toBe(bytesToHex(plaintext))
      }
    )
  }
})

// --------------------------------------------------------------------------
// Protobuf wire formats
// --------------------------------------------------------------------------

describe('protobuf wire format (omemo2 profile)', () => {
  const f = vectors.protos.fields
  const g = vectors.protos.omemo2

  it('OMEMOMessage round trip and golden bytes', () => {
    const decoded = decodeOmemoMessage(hex(g.omemoMessage))
    expect(decoded.n).toBe(f.n)
    expect(decoded.pn).toBe(f.pn)
    expectBytes(decoded.dhPub, f.dhPub)
    expectBytes(decoded.ciphertext as Uint8Array, f.ciphertext)
    expectBytes(
      encodeOmemoMessage({
        n: f.n,
        pn: f.pn,
        dhPub: hex(f.dhPub),
        ciphertext: hex(f.ciphertext)
      }),
      g.omemoMessage
    )
  })

  it('OMEMOAuthenticatedMessage golden bytes', () => {
    const decoded = decodeAuthenticatedMessage(hex(g.authenticatedMessage))
    expectBytes(decoded.mac, f.mac16)
    expectBytes(decoded.message, g.omemoMessage)
    expectBytes(
      encodeAuthenticatedMessage({ mac: hex(f.mac16), message: hex(g.omemoMessage) }),
      g.authenticatedMessage
    )
  })

  it('OMEMOKeyExchange golden bytes', () => {
    const decoded = decodeKeyExchange(hex(g.keyExchange))
    expect(decoded.pkId).toBe(f.pkId)
    expect(decoded.spkId).toBe(f.spkId)
    expectBytes(decoded.ik, f.ik32)
    expectBytes(decoded.ek, f.ek32)
    expectBytes(decoded.message, f.kexMessage)
    expectBytes(
      encodeKeyExchange({
        pkId: f.pkId,
        spkId: f.spkId,
        ik: hex(f.ik32),
        ek: hex(f.ek32),
        message: hex(f.kexMessage)
      }),
      g.keyExchange
    )
  })
})

describe('protobuf wire format (legacy profile)', () => {
  const f = vectors.protos.fields
  const g = vectors.protos.legacy

  it('legacy OMEMOMessage uses the reference field numbering', () => {
    // reference schema: dh_pub = 1, n = 2, pn = 3, ciphertext = 4
    const decoded = decodeOmemoMessage(hex(g.omemoMessage), 'legacy')
    expect(decoded.n).toBe(f.n)
    expect(decoded.pn).toBe(f.pn)
    expectBytes(decoded.dhPub, f.dhPubWire33)
    expectBytes(decoded.ciphertext as Uint8Array, f.ciphertext)
  })

  it('legacy authenticated message is message || mac8 concatenation', () => {
    const opened = PROFILES.legacy.open(hex(g.authenticatedMessage))
    expectBytes(opened.mac, f.mac8)
    expectBytes(opened.messageBytes, `33${g.omemoMessage}`)
    expectBytes(
      PROFILES.legacy.seal(hex(f.mac8), hex(`33${g.omemoMessage}`)),
      g.authenticatedMessage
    )
  })

  it('legacy OMEMOKeyExchange uses the reference field numbering', () => {
    // reference schema: pk_id = 1, ek = 2, ik = 3, message = 4, spk_id = 6,
    // with a leading 0x33 version byte
    const decoded = decodeKeyExchangeWire('legacy', hex(g.keyExchange))
    expect(decoded.pkId).toBe(f.pkId)
    expect(decoded.spkId).toBe(f.spkId)
    expectBytes(decoded.ik, f.ik33)
    // ek is returned without the legacy 0x05 type byte, i.e. the inner
    // 32 bytes of the wire form
    expectBytes(decoded.ek, f.ek33.slice(2))
    expectBytes(decoded.message, f.inner)
  })

  it('legacy OMEMOKeyExchange encoder produces the reference bytes', () => {
    expectBytes(
      encodeKeyExchangeWire(
        'legacy',
        { pkId: f.pkId, spkId: f.spkId, ik: hex(f.ik33), ek: hex(f.ek33) },
        hex(f.inner)
      ),
      g.keyExchange
    )
  })
})

// --------------------------------------------------------------------------
// XML wire format
// --------------------------------------------------------------------------

describe('encrypted element parsing (reference XML)', () => {
  it('legacy element', () => {
    const w = vectors.wire.legacy
    const parsed = parseEncryptedElement(parseXml(w.xml), 'legacy')
    expect(parsed.sid).toBe(w.sid)
    expect(parsed.keys.length).toBe(2)
    const byRid = new Map(parsed.keys.map((k) => [k.rid, k]))
    const kexKey = byRid.get(w.rids[0])
    const plainKey = byRid.get(w.rids[1])
    expect(kexKey?.kex).toBe(true)
    expect(plainKey?.kex).toBe(false)
    expectBytes(parsed.payload as Uint8Array, w.payloadCiphertext)
    expectBytes(parsed.iv as Uint8Array, w.iv)
    // the plain key content is the authenticated message: 0x33 || proto || mac8
    const data = plainKey?.data ?? new Uint8Array(0)
    expect(data[0]).toBe(0x33)
    const opened = PROFILES.legacy.open(data)
    expect(opened.mac.length).toBe(8)
  })

  it('omemo2 element', () => {
    const w = vectors.wire.omemo2
    const parsed = parseEncryptedElement(parseXml(w.xml), 'omemo2')
    expect(parsed.sid).toBe(w.sid)
    expect(parsed.keys.length).toBe(1)
    expect(parsed.keys[0]?.kex).toBe(true)
    expect(parsed.keys[0]?.jid).toBe(w.jid)
    expectBytes(parsed.payload as Uint8Array, w.payloadCiphertext)
    const kex = decodeKeyExchangeWire('omemo2', parsed.keys[0]?.data ?? new Uint8Array(0))
    expect(kex.spkId).toBe(42)
    expect(kex.pkId).toBe(7)
    const auth = decodeAuthenticatedMessage(kex.message)
    const inner = decodeOmemoMessage(auth.message)
    expect(inner.n).toBe(0)
    expect(inner.dhPub.length).toBe(32)
  })
})

describe('bundle parsing (reference XML)', () => {
  const x3dh = vectors.x3dh

  it('omemo2 bundle', () => {
    const parsed = parseBundle(parseXml(vectors.wire.omemo2Bundle.xml), 'omemo2')
    expect(parsed.signedPreKeyId).toBe(42)
    expectBytes(parsed.identityKeyWire, x3dh.omemo2.identityB.edPub)
    expectBytes(parsed.signedPreKey, x3dh.omemo2.signedPreKey.pub)
    // parseBundle already verified the signature against the identity key
    expect(parsed.signedPreKeySignature.length).toBe(64)
    expect(parsed.preKeys.map((p) => p.pkId)).toEqual([7])
    expectBytes(parsed.preKeys[0]?.pk ?? new Uint8Array(0), x3dh.omemo2.preKey.pub)
  })

  it('legacy bundle', () => {
    const parsed = parseBundle(parseXml(vectors.wire.legacyBundle.xml), 'legacy')
    expect(parsed.signedPreKeyId).toBe(42)
    expectBytes(parsed.identityKeyWire, `05${x3dh.legacy.identityB.curvePub}`)
    expectBytes(parsed.identityKeyCurve, x3dh.legacy.identityB.curvePub)
    expectBytes(parsed.signedPreKey, x3dh.legacy.signedPreKey.pub)
    expect(parsed.preKeys.map((p) => p.pkId)).toEqual([7])
    expectBytes(parsed.preKeys[0]?.pk ?? new Uint8Array(0), x3dh.legacy.preKey.pub)
    // the signature covers the 33 byte wire encoding of the signed pre key and
    // carries the identity key's Edwards sign bit
    expect(parsed.signedPreKeySignature.length).toBe(64)
  })
})

// --------------------------------------------------------------------------
// end to end: reference key exchange element feeds a full responder session
// --------------------------------------------------------------------------

describe('reference key exchange end to end', () => {
  it('omemo2 kex element decrypts to the payload key material', () => {
    const w = vectors.wire.omemo2
    const x3dh = vectors.x3dh.omemo2
    const parsed = parseEncryptedElement(parseXml(w.xml), 'omemo2')
    const kex = decodeKeyExchangeWire('omemo2', parsed.keys[0]?.data ?? new Uint8Array(0))

    const session = sessionResponder(PROFILES.omemo2, {
      sharedSecret: hex(x3dh.sharedSecret),
      associatedData: hex(x3dh.associatedData),
      ownRatchet: {
        privateKey: hex(x3dh.signedPreKey.priv),
        publicKey: hex(x3dh.signedPreKey.pub)
      },
      localIdentity: hex(x3dh.identityB.edPub),
      remoteIdentity: hex(x3dh.identityA.edPub)
    })
    const km = session.decrypt(kex.message)
    // key material = 32 byte payload key || 16 byte auth tag
    expectBytes(km, `${w.payloadKey}${w.payloadTag}`)
  })

  it('legacy kex element decrypts to the payload key material', () => {
    const w = vectors.wire.legacy
    const x3dh = vectors.x3dh.legacy
    const parsed = parseEncryptedElement(parseXml(w.xml), 'legacy')
    const kexKey = parsed.keys.find((k) => k.kex)
    expect(kexKey).toBeDefined()
    const kex = decodeKeyExchangeWire('legacy', kexKey?.data ?? new Uint8Array(0))
    expect(kex.pkId).toBe(7)
    expect(kex.spkId).toBe(42)
    expectBytes(kex.ik, `05${x3dh.identityA.curvePub}`)
    expectBytes(kex.ek, x3dh.ephemeral.pub)

    const session = sessionResponder(PROFILES.legacy, {
      sharedSecret: hex(x3dh.sharedSecret),
      associatedData: hex(x3dh.associatedData),
      ownRatchet: {
        privateKey: hex(x3dh.signedPreKey.priv),
        publicKey: hex(x3dh.signedPreKey.pub)
      },
      localIdentity: encodeCurveKeyWire(hex(x3dh.identityB.curvePub)),
      remoteIdentity: encodeCurveKeyWire(hex(x3dh.identityA.curvePub))
    })
    const km = session.decrypt(kex.message)
    // key material = 16 byte payload key || 16 byte GCM tag
    expectBytes(km, `${w.payloadKey}${w.payloadTag}`)
  })
})
