// Interoperability tests against the python-omemo reference stack
// (xeddsa / x3dh / doubleratchet / oldmemo / twomemo). Test vectors are
// generated by scripts/gen_vectors.py into vectors.json. A subset of tests
// call scripts/py_verify.py to let the reference stack verify or decrypt
// output produced by this implementation; those tests are skipped when the
// venv is not available.

import { spawn, type ChildProcess } from 'node:child_process'
import { existsSync, readFileSync, readSync, writeSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { afterAll, describe, expect, it } from 'vitest'

import { ed25519, x25519 } from '@noble/curves/ed25519.js'

import {
  aes128GcmDecrypt,
  aes128GcmEncrypt,
  aes256CbcDecrypt,
  aes256CbcEncrypt
} from '../../src/crypto/aes'
import { hkdfSha256 } from '../../src/crypto/kdf'
import {
  curvePublicToEdPublic,
  curveSecretSignBit,
  decodeCurveKeyWire,
  edPublicToCurvePublic,
  edSecretToCurveSecret,
  encodeCurveKeyWire,
  x25519SharedSecret
} from '../../src/crypto/keys'
import { xed25519Sign, xed25519Verify } from '../../src/crypto/xed25519'
import { bytesToHex, hexToBytes, utf8ToBytes } from '../../src/internal/bytes'
import { parseXml, serializeXml } from '../../src/internal/xml'
import { OmemoManager } from '../../src/manager'
import {
  decodeAuthenticatedMessage,
  decodeKeyExchange,
  decodeOmemoMessage,
  encodeAuthenticatedMessage,
  encodeKeyExchange,
  encodeOmemoMessage
} from '../../src/protocol/wire/messages'
import { PROFILES, unmarshalMessage } from '../../src/protocol/wire/profiles'
import { Session } from '../../src/protocol/session/session'
import type { SessionState } from '../../src/protocol/session/session'
import { sessionInitiator, sessionResponder } from '../../src/protocol/session/sessionInit'
import { serializeSceEnvelope, textEnvelope } from '../../src/protocol/wire/sce'
import { x3dhInitiate, x3dhRespond } from '../../src/protocol/session/x3dh'
import type { OwnBundle, ParsedBundle } from '../../src/protocol/wire/bundle'
import { parseBundle, serializeBundle } from '../../src/protocol/wire/bundle'
import { decodeKeyExchangeWire, encodeKeyExchangeWire } from '../../src/protocol/wire/keyExchange'
import { parseEncryptedElement, serializeEncrypted } from '../../src/protocol/wire/encrypted'
import { InMemoryOmemoStore } from '../../src/store/memory'
import type { Namespace } from '../../src/constants'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const PKG = path.resolve(HERE, '..', '..')
const PYTHON = path.join(PKG, '.venv', 'bin', 'python')
const BRIDGE = path.join(PKG, 'scripts', 'py_verify.py')
const HAS_PYTHON = existsSync(PYTHON)

const vectors = JSON.parse(readFileSync(path.join(HERE, 'vectors.json'), 'utf8'))

function hex(s: string): Uint8Array {
  return hexToBytes(s)
}

function expectBytes(actual: Uint8Array, expectedHex: string): void {
  expect(bytesToHex(actual)).toBe(expectedHex)
}

interface PyResult {
  ok: boolean
  error?: string
  [key: string]: unknown
}

// The bridge speaks one JSON request per stdin line and answers with one
// JSON response per stdout line. A single python process is kept alive for
// the whole test file so we do not pay interpreter and dependency startup
// cost per call. fs.writeSync and fs.readSync on the pipe file descriptors
// keep the interface synchronous.
let bridgeProc: ChildProcess | undefined
let bridgeBuf = Buffer.alloc(0)

// Short blocking sleep used while polling the non-blocking child pipe.
const waitCell = new Int32Array(new SharedArrayBuffer(4))

interface PipeHandle {
  _handle?: { fd?: number }
}

function py(request: Record<string, unknown>): PyResult {
  if (!bridgeProc || bridgeProc.exitCode !== null || bridgeProc.killed) {
    bridgeBuf = Buffer.alloc(0)
    bridgeProc = spawn(PYTHON, [BRIDGE], { stdio: ['pipe', 'pipe', 'inherit'] })
  }
  const stdinFd = (bridgeProc.stdin as PipeHandle)._handle?.fd
  const stdoutFd = (bridgeProc.stdout as PipeHandle)._handle?.fd
  if (stdinFd === undefined || stdoutFd === undefined) {
    throw new Error('python bridge pipes unavailable')
  }
  writeSync(stdinFd, `${JSON.stringify(request)}\n`)
  const chunk = Buffer.alloc(1 << 16)
  const deadline = Date.now() + 120_000
  for (;;) {
    const nl = bridgeBuf.indexOf(0x0a)
    if (nl >= 0) {
      const line = bridgeBuf.subarray(0, nl)
      bridgeBuf = bridgeBuf.subarray(nl + 1)
      return JSON.parse(line.toString('utf8')) as PyResult
    }
    try {
      const n = readSync(stdoutFd, chunk, 0, chunk.length, null)
      if (n <= 0) throw new Error('python bridge terminated unexpectedly')
      bridgeBuf = Buffer.concat([bridgeBuf, chunk.subarray(0, n)])
    } catch (e) {
      // the child pipe is non-blocking; EAGAIN just means no output yet
      if ((e as NodeJS.ErrnoException).code !== 'EAGAIN') throw e
      if (Date.now() > deadline) throw new Error('python bridge timed out')
      Atomics.wait(waitCell, 0, 0, 1)
    }
  }
}

afterAll(() => {
  bridgeProc?.kill()
  bridgeProc = undefined
})

// Map a reference DoubleRatchetModel dump (as emitted by gen_vectors.py) to
// our SessionState. own ratchet public key is rederived from the private key.
function sessionStateFromModel(
  model: Record<string, unknown>,
  initiation: 'active' | 'passive',
  ad: Uint8Array,
  localIdentity: Uint8Array,
  remoteIdentity: Uint8Array
): SessionState {
  const m = model as {
    ownRatchetPriv: string
    otherRatchetPub: string
    rootChain: { length: number; key: string } | null
    sendingChain: { length: number; key: string } | null
    receivingChain: { length: number; key: string } | null
    previousSendingChainLength: number | null
    skippedMessageKeys: { ratchetPub: string; index: number; messageKey: string }[]
  }
  const dhsPriv = hex(m.ownRatchetPriv)
  return {
    initiation,
    rk: hex(m.rootChain?.key ?? ''),
    cks: m.sendingChain === null ? null : hex(m.sendingChain.key),
    ckr: m.receivingChain === null ? null : hex(m.receivingChain.key),
    dhs: { privateKey: dhsPriv, publicKey: x25519.getPublicKey(dhsPriv) },
    dhr: m.otherRatchetPub === '' ? null : hex(m.otherRatchetPub),
    ns: m.sendingChain?.length ?? 0,
    nr: m.receivingChain?.length ?? 0,
    pn: m.previousSendingChainLength ?? 0,
    ad,
    remoteIdentity,
    localIdentity,
    pendingKeyExchange: null,
    skipped: m.skippedMessageKeys.map((k) => ({
      dh: hex(k.ratchetPub),
      n: k.index,
      mk: hex(k.messageKey)
    })),
    confirmed: false
  }
}

function wireIdentity(ns: Namespace, identity: { curvePub: string; edPub: string }): Uint8Array {
  return ns === 'legacy' ? encodeCurveKeyWire(hex(identity.curvePub)) : hex(identity.edPub)
}

// --------------------------------------------------------------------------
// symmetric primitives
// --------------------------------------------------------------------------

describe('HKDF-SHA256 (RFC 5869)', () => {
  for (const [i, c] of vectors.hkdf.cases.entries()) {
    it(`test case ${i + 1}`, () => {
      const okm = hkdfSha256(hex(c.ikm), hex(c.salt), hex(c.info), c.length)
      expectBytes(okm, c.okm)
      // undefined salt must behave like a 32 byte zero salt
      const zeroSalt = new Uint8Array(32)
      const okm2 = hkdfSha256(hex(c.ikm), undefined, hex(c.info), c.length)
      const okm3 = hkdfSha256(hex(c.ikm), zeroSalt, hex(c.info), c.length)
      expect(bytesToHex(okm2)).toBe(bytesToHex(okm3))
    })
  }
})

describe('AES vectors', () => {
  for (const [i, c] of vectors.aes.cbc.entries()) {
    it(`AES-256-CBC vector ${i + 1}`, () => {
      expectBytes(aes256CbcEncrypt(hex(c.key), hex(c.iv), hex(c.plaintext)), c.ciphertext)
      expectBytes(aes256CbcDecrypt(hex(c.key), hex(c.iv), hex(c.ciphertext)), c.plaintext)
    })
  }
  for (const [i, c] of vectors.aes.gcm.entries()) {
    it(`AES-128-GCM vector ${i + 1}`, () => {
      const res = aes128GcmEncrypt(hex(c.key), hex(c.iv), hex(c.plaintext))
      expectBytes(res.ciphertext, c.ciphertext)
      expectBytes(res.tag, c.tag)
      expectBytes(
        aes128GcmDecrypt(hex(c.key), hex(c.iv), hex(c.ciphertext), hex(c.tag)),
        c.plaintext
      )
    })
  }
})

// --------------------------------------------------------------------------
// XEdDSA and key conversion
// --------------------------------------------------------------------------

describe('XEdDSA (python-xeddsa vectors)', () => {
  const msg = hex(vectors.xeddsa.message)

  for (const [i, c] of vectors.xeddsa.cases.entries()) {
    it(`vector ${i + 1}: reference signature verifies under our rules`, () => {
      const res = xed25519Verify(encodeCurveKeyWire(hex(c.curvePub)), msg, hex(c.signature))
      expect(res.valid).toBe(true)
      expectBytes(res.ed25519PublicKey, c.edPub)
    })

    it(`vector ${i + 1}: sign bit matches`, () => {
      expect(curveSecretSignBit(hex(c.priv))).toBe(c.signBit)
      // the smuggled bit in the reference signature is the same bit
      expect((hex(c.signature)[63] ?? 0) >> 7).toBe(c.signBit)
    })

    it(`vector ${i + 1}: our signature verifies and carries the sign bit`, () => {
      const sig = xed25519Sign(hex(c.priv), msg)
      expect((sig[63] ?? 0) >> 7).toBe(c.signBit)
      const res = xed25519Verify(encodeCurveKeyWire(hex(c.curvePub)), msg, sig)
      expect(res.valid).toBe(true)
      expectBytes(res.ed25519PublicKey, c.edPub)
      const flipped = Uint8Array.from(sig)
      flipped[10] = (flipped[10] ?? 0) ^ 1
      expect(xed25519Verify(encodeCurveKeyWire(hex(c.curvePub)), msg, flipped).valid).toBe(false)
    })

    it.skipIf(!HAS_PYTHON)(`vector ${i + 1}: our signature verifies under xeddsa`, () => {
      const sig = xed25519Sign(hex(c.priv), msg)
      const res = py({
        op: 'xeddsa_verify_curve',
        curvePub: c.curvePub,
        signBit: c.signBit,
        msg: vectors.xeddsa.message,
        sig: bytesToHex(sig)
      })
      expect(res.ok).toBe(true)
      expect(res.valid).toBe(true)
    })
  }
})

describe('Ed25519 <-> Curve25519 conversion', () => {
  for (const [i, c] of vectors.edCurve.cases.entries()) {
    it(`vector ${i + 1}`, () => {
      expectBytes(edSecretToCurveSecret(hex(c.seed)), c.curvePriv)
      expectBytes(edPublicToCurvePublic(hex(c.edPub)), c.curvePub)
      expectBytes(curvePublicToEdPublic(hex(c.curvePub), 0), c.edFromCurveSign0)
      expectBytes(curvePublicToEdPublic(hex(c.curvePub), 1), c.edFromCurveSign1)
      expectBytes(encodeCurveKeyWire(hex(c.curvePub)), c.wire)
      expectBytes(decodeCurveKeyWire(hex(c.wire)), c.curvePub)
      expectBytes(decodeCurveKeyWire(hex(c.curvePub)), c.curvePub)
    })
  }
})

describe('X25519 shared secrets', () => {
  for (const [i, c] of vectors.x25519.cases.entries()) {
    it(`vector ${i + 1}`, () => {
      expectBytes(x25519SharedSecret(hex(c.priv), hex(c.pub)), c.shared)
    })
  }
})

// --------------------------------------------------------------------------
// X3DH
// --------------------------------------------------------------------------

describe('X3DH key agreement', () => {
  for (const ns of ['omemo2', 'legacy'] as const) {
    const v = vectors.x3dh[ns]

    it(`${ns}: passive side reproduces reference shared secret and AD`, () => {
      const profile = PROFILES[ns]
      const own =
        ns === 'legacy'
          ? {
              privateKey: hex(v.identityB.priv),
              publicKey: hex(v.identityB.curvePub),
              wirePublicKey: encodeCurveKeyWire(hex(v.identityB.curvePub))
            }
          : {
              privateKey: hex(v.identityB.seed),
              publicKey: hex(v.identityB.edPub),
              wirePublicKey: hex(v.identityB.edPub)
            }
      const res = x3dhRespond(profile, own, {
        ik: wireIdentity(ns, v.identityA),
        ek: hex(v.ephemeral.pub),
        spkId: v.signedPreKey.id,
        pkId: v.preKey.id,
        signedPreKey: {
          privateKey: hex(v.signedPreKey.priv),
          publicKey: hex(v.signedPreKey.pub)
        },
        preKey: { privateKey: hex(v.preKey.priv), publicKey: hex(v.preKey.pub) }
      })
      expectBytes(res.sharedSecret, v.sharedSecret)
      expectBytes(res.associatedData, v.associatedData)
    })

    it.skipIf(!HAS_PYTHON)(
      `${ns}: our active side produces a secret the reference passive side derives`,
      () => {
        const profile = PROFILES[ns]
        const bundle: ParsedBundle = {
          namespace: ns,
          identityKeyWire: wireIdentity(ns, v.identityB),
          identityKeyCurve: hex(v.identityB.curvePub),
          identityKeyEd: hex(v.identityB.edPub),
          signedPreKeyId: v.signedPreKey.id,
          signedPreKey: hex(v.signedPreKey.pub),
          signedPreKeySignature: hex(v.signedPreKey.sig),
          preKeys: [{ pkId: v.preKey.id, pk: hex(v.preKey.pub) }]
        }
        const own =
          ns === 'legacy'
            ? {
                privateKey: hex(v.identityA.priv),
                publicKey: hex(v.identityA.curvePub),
                wirePublicKey: encodeCurveKeyWire(hex(v.identityA.curvePub))
              }
            : {
                privateKey: hex(v.identityA.seed),
                publicKey: hex(v.identityA.edPub),
                wirePublicKey: hex(v.identityA.edPub)
              }
        const res = x3dhInitiate(profile, own, bundle, { random: () => 0 })
        const pyRes = py({
          op: 'x3dh_passive',
          profile: ns,
          ikPriv: v.identityB.priv,
          spkPriv: v.signedPreKey.priv,
          pkPriv: v.preKey.priv,
          header: {
            ikEdPub: v.identityA.edPub,
            ek: bytesToHex(res.ephemeral.publicKey),
            spkPub: v.signedPreKey.pub,
            pkPub: v.preKey.pub
          }
        })
        expect(pyRes.ok).toBe(true)
        expect(bytesToHex(res.sharedSecret)).toBe(pyRes.sharedSecret)
        expect(bytesToHex(res.associatedData)).toBe(pyRes.associatedData)
        expect(res.preKeyId).toBe(v.preKey.id)
        expect(res.signedPreKeyId).toBe(v.signedPreKey.id)
      }
    )
  }
})

// --------------------------------------------------------------------------
// Double ratchet
// --------------------------------------------------------------------------

describe('double ratchet session (python encrypt -> our decrypt)', () => {
  for (const ns of ['omemo2', 'legacy'] as const) {
    const profile = PROFILES[ns]
    const x3dh = vectors.x3dh[ns]
    const dr = vectors.ratchet[ns]
    const ad = hex(x3dh.associatedData)
    const ikA = wireIdentity(ns, x3dh.identityA)
    const ikB = wireIdentity(ns, x3dh.identityB)

    function responderSession(): Session {
      return sessionResponder(profile, {
        sharedSecret: hex(x3dh.sharedSecret),
        associatedData: ad,
        ownRatchet: {
          privateKey: hex(x3dh.signedPreKey.priv),
          publicKey: hex(x3dh.signedPreKey.pub)
        },
        localIdentity: ikB,
        remoteIdentity: ikA
      })
    }

    it(`${ns}: responder decrypts the reference initiator messages in order`, () => {
      const session = responderSession()
      for (const m of dr.aliceToBob) {
        expectBytes(session.decrypt(hex(m.wire.ciphertext)), m.plaintext)
      }
    })

    it(`${ns}: responder handles out-of-order delivery`, () => {
      const session = responderSession()
      const [m1, m2, m3] = dr.aliceToBob
      expectBytes(session.decrypt(hex(m1.wire.ciphertext)), m1.plaintext)
      expectBytes(session.decrypt(hex(m3.wire.ciphertext)), m3.plaintext)
      // after skipping index 1 the skipped store must hold the reference key
      const skipped = session.state.skipped
      const refSkipped = dr.bobModelOutOfOrder.skippedMessageKeys
      expect(skipped.length).toBe(refSkipped.length)
      for (const [i, ref] of refSkipped.entries()) {
        const entry = skipped[i]
        expect(entry).toBeDefined()
        expectBytes(entry!.dh, ref.ratchetPub)
        expect(entry!.n).toBe(ref.index)
        expectBytes(entry!.mk, ref.messageKey)
      }
      expectBytes(session.decrypt(hex(m2.wire.ciphertext)), m2.plaintext)
    })

    it(`${ns}: initiator-side session decrypts the reference reply`, () => {
      const state = sessionStateFromModel(dr.aliceModelAfterSend3, 'active', ad, ikA, ikB)
      const session = new Session(profile, state)
      expectBytes(session.decrypt(hex(dr.bobReply.wire.ciphertext)), dr.bobReply.plaintext)
    })

    it.skipIf(!HAS_PYTHON)(
      `${ns}: our initiator-side encryption decrypts on the reference side`,
      () => {
        const state = sessionStateFromModel(dr.aliceModelAfterSend3, 'active', ad, ikA, ikB)
        const session = new Session(profile, state)
        const plaintext = new Uint8Array([1, 2, 3, 4, 5, 42])
        const encrypted = session.encrypt(plaintext)
        const res = py({
          op: 'dr_decrypt',
          profile: ns,
          model: dr.bobModelFinal,
          ad: x3dh.associatedData,
          wire: {
            ratchetPub: dr.aliceRatchet.pub,
            pn: 0,
            n: 3,
            ciphertext: bytesToHex(encrypted.wire)
          }
        })
        expect(res.ok).toBe(true)
        expect(res.plaintext).toBe(bytesToHex(plaintext))
      }
    )
  }
})

// --------------------------------------------------------------------------
// Protobuf wire formats
// --------------------------------------------------------------------------

describe('protobuf wire format (omemo2 profile)', () => {
  const f = vectors.protos.fields
  const g = vectors.protos.omemo2

  it('OMEMOMessage round trip and golden bytes', () => {
    const decoded = decodeOmemoMessage(hex(g.omemoMessage))
    expect(decoded.n).toBe(f.n)
    expect(decoded.pn).toBe(f.pn)
    expectBytes(decoded.dhPub, f.dhPub)
    expectBytes(decoded.ciphertext as Uint8Array, f.ciphertext)
    expectBytes(
      encodeOmemoMessage({
        n: f.n,
        pn: f.pn,
        dhPub: hex(f.dhPub),
        ciphertext: hex(f.ciphertext)
      }),
      g.omemoMessage
    )
  })

  it('OMEMOAuthenticatedMessage golden bytes', () => {
    const decoded = decodeAuthenticatedMessage(hex(g.authenticatedMessage))
    expectBytes(decoded.mac, f.mac16)
    expectBytes(decoded.message, g.omemoMessage)
    expectBytes(
      encodeAuthenticatedMessage({ mac: hex(f.mac16), message: hex(g.omemoMessage) }),
      g.authenticatedMessage
    )
  })

  it('OMEMOKeyExchange golden bytes', () => {
    const decoded = decodeKeyExchange(hex(g.keyExchange))
    expect(decoded.pkId).toBe(f.pkId)
    expect(decoded.spkId).toBe(f.spkId)
    expectBytes(decoded.ik, f.ik32)
    expectBytes(decoded.ek, f.ek32)
    expectBytes(decoded.message, f.kexMessage)
    expectBytes(
      encodeKeyExchange({
        pkId: f.pkId,
        spkId: f.spkId,
        ik: hex(f.ik32),
        ek: hex(f.ek32),
        message: hex(f.kexMessage)
      }),
      g.keyExchange
    )
  })
})

describe('protobuf wire format (legacy profile)', () => {
  const f = vectors.protos.fields
  const g = vectors.protos.legacy

  it('legacy OMEMOMessage uses the reference field numbering', () => {
    // reference schema: dh_pub = 1, n = 2, pn = 3, ciphertext = 4
    const decoded = decodeOmemoMessage(hex(g.omemoMessage), 'legacy')
    expect(decoded.n).toBe(f.n)
    expect(decoded.pn).toBe(f.pn)
    expectBytes(decoded.dhPub, f.dhPubWire33)
    expectBytes(decoded.ciphertext as Uint8Array, f.ciphertext)
  })

  it('legacy authenticated message is message || mac8 concatenation', () => {
    const opened = PROFILES.legacy.open(hex(g.authenticatedMessage))
    expectBytes(opened.mac, f.mac8)
    expectBytes(opened.messageBytes, `33${g.omemoMessage}`)
    expectBytes(
      PROFILES.legacy.seal(hex(f.mac8), hex(`33${g.omemoMessage}`)),
      g.authenticatedMessage
    )
  })

  it('legacy OMEMOKeyExchange uses the reference field numbering', () => {
    // reference schema: pk_id = 1, ek = 2, ik = 3, message = 4, spk_id = 6,
    // with a leading 0x33 version byte
    const decoded = decodeKeyExchangeWire('legacy', hex(g.keyExchange))
    expect(decoded.pkId).toBe(f.pkId)
    expect(decoded.spkId).toBe(f.spkId)
    expectBytes(decoded.ik, f.ik33)
    // ek is returned without the legacy 0x05 type byte, i.e. the inner
    // 32 bytes of the wire form
    expectBytes(decoded.ek, f.ek33.slice(2))
    expectBytes(decoded.message, f.inner)
  })

  it('legacy OMEMOKeyExchange encoder produces the reference bytes', () => {
    expectBytes(
      encodeKeyExchangeWire(
        'legacy',
        { pkId: f.pkId, spkId: f.spkId, ik: hex(f.ik33), ek: hex(f.ek33) },
        hex(f.inner)
      ),
      g.keyExchange
    )
  })
})

// --------------------------------------------------------------------------
// XML wire format
// --------------------------------------------------------------------------

describe('encrypted element parsing (reference XML)', () => {
  it('legacy element', () => {
    const w = vectors.wire.legacy
    const parsed = parseEncryptedElement(parseXml(w.xml), 'legacy')
    expect(parsed.sid).toBe(w.sid)
    expect(parsed.keys.length).toBe(2)
    const byRid = new Map(parsed.keys.map((k) => [k.rid, k]))
    const kexKey = byRid.get(w.rids[0])
    const plainKey = byRid.get(w.rids[1])
    expect(kexKey?.kex).toBe(true)
    expect(plainKey?.kex).toBe(false)
    expectBytes(parsed.payload as Uint8Array, w.payloadCiphertext)
    expectBytes(parsed.iv as Uint8Array, w.iv)
    // the plain key content is the authenticated message: 0x33 || proto || mac8
    const data = plainKey?.data ?? new Uint8Array(0)
    expect(data[0]).toBe(0x33)
    const opened = PROFILES.legacy.open(data)
    expect(opened.mac.length).toBe(8)
  })

  it('omemo2 element', () => {
    const w = vectors.wire.omemo2
    const parsed = parseEncryptedElement(parseXml(w.xml), 'omemo2')
    expect(parsed.sid).toBe(w.sid)
    expect(parsed.keys.length).toBe(1)
    expect(parsed.keys[0]?.kex).toBe(true)
    expect(parsed.keys[0]?.jid).toBe(w.jid)
    expectBytes(parsed.payload as Uint8Array, w.payloadCiphertext)
    const kex = decodeKeyExchangeWire('omemo2', parsed.keys[0]?.data ?? new Uint8Array(0))
    expect(kex.spkId).toBe(42)
    expect(kex.pkId).toBe(7)
    const auth = decodeAuthenticatedMessage(kex.message)
    const inner = decodeOmemoMessage(auth.message)
    expect(inner.n).toBe(0)
    expect(inner.dhPub.length).toBe(32)
  })
})

describe('bundle parsing (reference XML)', () => {
  const x3dh = vectors.x3dh

  it('omemo2 bundle', () => {
    const parsed = parseBundle(parseXml(vectors.wire.omemo2Bundle.xml), 'omemo2')
    expect(parsed.signedPreKeyId).toBe(42)
    expectBytes(parsed.identityKeyWire, x3dh.omemo2.identityB.edPub)
    expectBytes(parsed.signedPreKey, x3dh.omemo2.signedPreKey.pub)
    // parseBundle already verified the signature against the identity key
    expect(parsed.signedPreKeySignature.length).toBe(64)
    expect(parsed.preKeys.map((p) => p.pkId)).toEqual([7])
    expectBytes(parsed.preKeys[0]?.pk ?? new Uint8Array(0), x3dh.omemo2.preKey.pub)
  })

  it('legacy bundle', () => {
    const parsed = parseBundle(parseXml(vectors.wire.legacyBundle.xml), 'legacy')
    expect(parsed.signedPreKeyId).toBe(42)
    expectBytes(parsed.identityKeyWire, `05${x3dh.legacy.identityB.curvePub}`)
    expectBytes(parsed.identityKeyCurve, x3dh.legacy.identityB.curvePub)
    expectBytes(parsed.signedPreKey, x3dh.legacy.signedPreKey.pub)
    expect(parsed.preKeys.map((p) => p.pkId)).toEqual([7])
    expectBytes(parsed.preKeys[0]?.pk ?? new Uint8Array(0), x3dh.legacy.preKey.pub)
    // the signature covers the 33 byte wire encoding of the signed pre key and
    // carries the identity key's Edwards sign bit
    expect(parsed.signedPreKeySignature.length).toBe(64)
  })
})

// --------------------------------------------------------------------------
// end to end: reference key exchange element feeds a full responder session
// --------------------------------------------------------------------------

describe('reference key exchange end to end', () => {
  it('omemo2 kex element decrypts to the payload key material', () => {
    const w = vectors.wire.omemo2
    const x3dh = vectors.x3dh.omemo2
    const parsed = parseEncryptedElement(parseXml(w.xml), 'omemo2')
    const kex = decodeKeyExchangeWire('omemo2', parsed.keys[0]?.data ?? new Uint8Array(0))

    const session = sessionResponder(PROFILES.omemo2, {
      sharedSecret: hex(x3dh.sharedSecret),
      associatedData: hex(x3dh.associatedData),
      ownRatchet: {
        privateKey: hex(x3dh.signedPreKey.priv),
        publicKey: hex(x3dh.signedPreKey.pub)
      },
      localIdentity: hex(x3dh.identityB.edPub),
      remoteIdentity: hex(x3dh.identityA.edPub)
    })
    const km = session.decrypt(kex.message)
    // key material = 32 byte payload key || 16 byte auth tag
    expectBytes(km, `${w.payloadKey}${w.payloadTag}`)
  })

  it('legacy kex element decrypts to the payload key material', () => {
    const w = vectors.wire.legacy
    const x3dh = vectors.x3dh.legacy
    const parsed = parseEncryptedElement(parseXml(w.xml), 'legacy')
    const kexKey = parsed.keys.find((k) => k.kex)
    expect(kexKey).toBeDefined()
    const kex = decodeKeyExchangeWire('legacy', kexKey?.data ?? new Uint8Array(0))
    expect(kex.pkId).toBe(7)
    expect(kex.spkId).toBe(42)
    expectBytes(kex.ik, `05${x3dh.identityA.curvePub}`)
    expectBytes(kex.ek, x3dh.ephemeral.pub)

    const session = sessionResponder(PROFILES.legacy, {
      sharedSecret: hex(x3dh.sharedSecret),
      associatedData: hex(x3dh.associatedData),
      ownRatchet: {
        privateKey: hex(x3dh.signedPreKey.priv),
        publicKey: hex(x3dh.signedPreKey.pub)
      },
      localIdentity: encodeCurveKeyWire(hex(x3dh.identityB.curvePub)),
      remoteIdentity: encodeCurveKeyWire(hex(x3dh.identityA.curvePub))
    })
    const km = session.decrypt(kex.message)
    // key material = 16 byte payload key || 16 byte GCM tag
    expectBytes(km, `${w.payloadKey}${w.payloadTag}`)
  })
})

// --------------------------------------------------------------------------
// live bidirectional interop through the python bridge
// --------------------------------------------------------------------------

const ALICE_JID = 'alice@example.org'
const BOB_JID = 'bob@example.org'
const ALICE_DEVICE = 0x00c0ffee
const BOB_DEVICE = 0x0badcafe

describe('python reference bridge', () => {
  it('is available and answers a trivial request', () => {
    // This test intentionally does not skip: without the venv the whole
    // bidirectional interop coverage below would be silently absent.
    expect(HAS_PYTHON).toBe(true)
    const res = py({
      op: 'x25519',
      priv: vectors.x25519.privs[0],
      pub: vectors.x25519.pubs[1]
    })
    expect(res.ok).toBe(true)
    console.log('python-backed interop tests are running against packages/omemo/.venv')
  })
})

interface IdentityVectors {
  seed: string
  priv: string
  edPub: string
  curvePub: string
}

// Identity material for our side, derived from the vector sets so that the
// same identities appear on both sides of the bridge.
function identityMaterial(ns: Namespace, identity: IdentityVectors) {
  return ns === 'legacy'
    ? {
        privateKey: hex(identity.priv),
        publicKey: hex(identity.curvePub),
        wirePublicKey: encodeCurveKeyWire(hex(identity.curvePub))
      }
    : {
        privateKey: hex(identity.seed),
        publicKey: hex(identity.edPub),
        wirePublicKey: hex(identity.edPub)
      }
}

// The Ed25519 sign bit a legacy identity smuggles into signatures. The
// reference responder needs it to reconstruct the initiator identity key.
function signBitOf(identity: IdentityVectors): number {
  return (hex(identity.edPub)[31] ?? 0) >> 7
}

// Associated data in the order the reference sender uses it. For the legacy
// profile the sender identity always comes first, so a passive (responder)
// sender sees the swapped form.
function adForSender(ns: Namespace, initiation: 'active' | 'passive', adHex: string): string {
  return bytesToHex(PROFILES[ns].adForSender(initiation, hex(adHex)))
}

// Extract the ratchet header fields the bridge needs from a sealed wire
// message produced by Session.encrypt.
function wireToBridge(ns: Namespace, wire: Uint8Array) {
  const { messageBytes } = PROFILES[ns].open(wire)
  const parsed = decodeOmemoMessage(unmarshalMessage(PROFILES[ns], messageBytes), ns)
  return {
    ratchetPub: bytesToHex(PROFILES[ns].decodeHeaderKey(parsed.dhPub)),
    pn: parsed.pn,
    n: parsed.n,
    ciphertext: bytesToHex(wire)
  }
}

// A responder bundle built by our serializer from vector material, consumed
// by the reference parser on the python side.
function ownBundle(ns: Namespace): OwnBundle {
  const x3dh = vectors.x3dh[ns]
  const bundle: OwnBundle = {
    namespace: ns,
    deviceId: BOB_DEVICE,
    signedPreKeyId: x3dh.signedPreKey.id,
    signedPreKeyPublic: hex(x3dh.signedPreKey.pub),
    signedPreKeySignature:
      ns === 'omemo2'
        ? ed25519.sign(hex(x3dh.signedPreKey.pub), hex(x3dh.identityB.seed))
        : xed25519Sign(hex(x3dh.identityB.priv), encodeCurveKeyWire(hex(x3dh.signedPreKey.pub))),
    identityKeyWire: wireIdentity(ns, x3dh.identityB),
    preKeys: [{ pkId: x3dh.preKey.id, pk: hex(x3dh.preKey.pub) }]
  }
  if (ns === 'legacy') {
    bundle.identityKeyCurve = hex(x3dh.identityB.curvePub)
    bundle.identityKeyEdSign = signBitOf(x3dh.identityB) as 0 | 1
  }
  return bundle
}

// A reference-produced responder bundle for the TS initiator side.
function pyBundle(ns: Namespace): { xml: string; parsed: ParsedBundle } {
  const x3dh = vectors.x3dh[ns]
  const res = py({
    op: 'bundle_serialize',
    profile: ns,
    ikPriv: x3dh.identityB.priv,
    spkPriv: x3dh.signedPreKey.priv,
    spkId: x3dh.signedPreKey.id,
    pkPrivs: [x3dh.preKey.priv],
    pkIds: [x3dh.preKey.id],
    jid: BOB_JID,
    deviceId: BOB_DEVICE
  })
  expect(res.ok).toBe(true)
  return { xml: res.xml as string, parsed: parseBundle(parseXml(res.xml as string), ns) }
}

async function managerFor(
  ns: Namespace,
  identity: IdentityVectors,
  jid: string,
  deviceId: number
): Promise<OmemoManager> {
  const store = new InMemoryOmemoStore()
  await store.putIdentity(identityMaterial(ns, identity))
  return OmemoManager.create({ namespace: ns, store, ownJid: jid, deviceId, preKeyCount: 1 })
}

function envelope(ns: Namespace, body: string): Uint8Array {
  return ns === 'omemo2' ? utf8ToBytes(serializeSceEnvelope(textEnvelope(body))) : utf8ToBytes(body)
}

describe.skipIf(!HAS_PYTHON)('key exchange interop through the bridge', () => {
  for (const ns of ['omemo2', 'legacy'] as const) {
    const profile = PROFILES[ns]
    const x3dh = vectors.x3dh[ns]
    const dr = vectors.ratchet[ns]

    it(
      `${ns}: our initiator session is accepted by the reference responder`,
      { timeout: 60_000 },
      () => {
        // reference-produced responder bundle, parsed by our parseBundle
        const bundle = pyBundle(ns)
        expectBytes(bundle.parsed.signedPreKey, x3dh.signedPreKey.pub)
        expectBytes(bundle.parsed.preKeys[0]?.pk ?? new Uint8Array(0), x3dh.preKey.pub)

        const alice = identityMaterial(ns, x3dh.identityA)
        const init = x3dhInitiate(profile, alice, bundle.parsed, { random: () => 0 })
        const keyExchange = {
          pkId: init.preKeyId,
          spkId: init.signedPreKeyId,
          ik: alice.wirePublicKey,
          ek:
            ns === 'legacy'
              ? encodeCurveKeyWire(init.ephemeral.publicKey)
              : init.ephemeral.publicKey
        }
        const session = sessionInitiator(profile, {
          sharedSecret: init.sharedSecret,
          associatedData: init.associatedData,
          responderRatchetPublic: init.signedPreKeyPublic,
          localIdentity: alice.wirePublicKey,
          remoteIdentity: bundle.parsed.identityKeyWire,
          keyExchange
        })

        const keyMaterial = hex(vectors.wire[ns].payloadKey + vectors.wire[ns].payloadTag)
        const encrypted = session.encrypt(keyMaterial)
        expect(encrypted.keyExchange).not.toBeNull()
        const kexData = encodeKeyExchangeWire(ns, encrypted.keyExchange!, encrypted.wire)

        // the reference responder parses our kex wire bytes, runs passive
        // X3DH and decrypts the wrapped ratchet message
        const acc = py({
          op: 'kex_accept',
          profile: ns,
          kexData: bytesToHex(kexData),
          ikPriv: x3dh.identityB.priv,
          spkPriv: x3dh.signedPreKey.priv,
          pkPriv: x3dh.preKey.priv,
          ikSignBit: signBitOf(x3dh.identityA),
          ratchetPriv: dr.bobRatchet.priv
        })
        expect(acc.ok).toBe(true)
        expect(acc.plaintext).toBe(bytesToHex(keyMaterial))
        expect(acc.sharedSecret).toBe(bytesToHex(init.sharedSecret))
        expect(acc.associatedData).toBe(bytesToHex(init.associatedData))
        expect(acc.spkId).toBe(x3dh.signedPreKey.id)
        expect(acc.pkId).toBe(x3dh.preKey.id)
      }
    )

    it(
      `${ns}: a reference-initiated key exchange drives our responder session`,
      { timeout: 60_000 },
      () => {
        // our responder bundle, serialized by our code and parsed by the
        // reference stack during its active X3DH (which also verifies the
        // signed pre key signature)
        const bundleXml = serializeBundle(ownBundle(ns))
        const km = hex(vectors.protos.fields.ciphertext)
        const built = py({
          op: 'kex_build',
          profile: ns,
          ikPriv: x3dh.identityA.priv,
          bundleXml,
          bundleJid: BOB_JID,
          bundleDeviceId: BOB_DEVICE,
          plaintext: bytesToHex(km),
          ekPriv: x3dh.ephemeral.priv,
          ratchetPriv: dr.aliceRatchet.priv
        })
        expect(built.ok).toBe(true)
        // with the same ephemeral key the reference reproduces the golden
        // shared secret and associated data
        expect(built.sharedSecret).toBe(x3dh.sharedSecret)
        expect(built.associatedData).toBe(x3dh.associatedData)

        const kex = decodeKeyExchangeWire(ns, hex(built.kexData as string))
        expect(kex.pkId).toBe(x3dh.preKey.id)
        expect(kex.spkId).toBe(x3dh.signedPreKey.id)

        const bob = identityMaterial(ns, x3dh.identityB)
        const respond = x3dhRespond(profile, bob, {
          ik: kex.ik,
          ek: kex.ek,
          spkId: kex.spkId,
          pkId: kex.pkId,
          signedPreKey: {
            privateKey: hex(x3dh.signedPreKey.priv),
            publicKey: hex(x3dh.signedPreKey.pub)
          },
          preKey: { privateKey: hex(x3dh.preKey.priv), publicKey: hex(x3dh.preKey.pub) }
        })
        expectBytes(respond.sharedSecret, built.sharedSecret as string)
        expectBytes(respond.associatedData, built.associatedData as string)

        const session = sessionResponder(profile, {
          sharedSecret: respond.sharedSecret,
          associatedData: respond.associatedData,
          ownRatchet: respond.signedPreKey,
          localIdentity: bob.wirePublicKey,
          remoteIdentity: kex.ik,
          keyExchange: { pkId: kex.pkId, spkId: kex.spkId, ik: kex.ik, ek: kex.ek }
        })
        expectBytes(session.decrypt(kex.message), bytesToHex(km))

        // and our reply decrypts on the reference side
        const reply = utf8ToBytes('responder reply')
        const out = session.encrypt(reply)
        const res = py({
          op: 'dr_decrypt',
          profile: ns,
          model: built.model,
          wire: wireToBridge(ns, out.wire),
          ad: adForSender(ns, 'passive', built.associatedData as string)
        })
        expect(res.ok).toBe(true)
        expect(res.plaintext).toBe(bytesToHex(reply))
      }
    )

    it(`${ns}: alternating exchange with out-of-order delivery`, { timeout: 120_000 }, () => {
      // TS initiator against the reference-produced bundle
      const bundle = pyBundle(ns)
      const alice = identityMaterial(ns, x3dh.identityA)
      const init = x3dhInitiate(profile, alice, bundle.parsed, { random: () => 0 })
      const session = sessionInitiator(profile, {
        sharedSecret: init.sharedSecret,
        associatedData: init.associatedData,
        responderRatchetPublic: init.signedPreKeyPublic,
        localIdentity: alice.wirePublicKey,
        remoteIdentity: bundle.parsed.identityKeyWire,
        keyExchange: {
          pkId: init.preKeyId,
          spkId: init.signedPreKeyId,
          ik: alice.wirePublicKey,
          ek:
            ns === 'legacy'
              ? encodeCurveKeyWire(init.ephemeral.publicKey)
              : init.ephemeral.publicKey
        }
      })
      const ad = bytesToHex(init.associatedData)

      // TS -> py: first message, accepted as a key exchange
      const m1 = session.encrypt(utf8ToBytes('exchange m1'))
      const acc = py({
        op: 'kex_accept',
        profile: ns,
        kexData: bytesToHex(encodeKeyExchangeWire(ns, m1.keyExchange!, m1.wire)),
        ikPriv: x3dh.identityB.priv,
        spkPriv: x3dh.signedPreKey.priv,
        pkPriv: x3dh.preKey.priv,
        ikSignBit: signBitOf(x3dh.identityA),
        ratchetPriv: dr.bobRatchet.priv
      })
      expect(acc.ok).toBe(true)
      expect(acc.plaintext).toBe(bytesToHex(utf8ToBytes('exchange m1')))
      let model = acc.model

      // py -> TS: reply
      const r1 = py({
        op: 'dr_encrypt',
        profile: ns,
        model,
        plaintext: bytesToHex(utf8ToBytes('exchange r1')),
        ad: adForSender(ns, 'passive', ad)
      })
      expect(r1.ok).toBe(true)
      model = r1.model
      expectBytes(
        session.decrypt(hex((r1.wire as { ciphertext: string }).ciphertext)),
        bytesToHex(utf8ToBytes('exchange r1'))
      )

      // TS -> py twice, delivered out of order on the reference side
      const m2 = session.encrypt(utf8ToBytes('exchange m2'))
      const m3 = session.encrypt(utf8ToBytes('exchange m3'))
      const d3 = py({
        op: 'dr_decrypt',
        profile: ns,
        model,
        wire: wireToBridge(ns, m3.wire),
        ad
      })
      expect(d3.ok).toBe(true)
      expect(d3.plaintext).toBe(bytesToHex(utf8ToBytes('exchange m3')))
      const d2 = py({
        op: 'dr_decrypt',
        profile: ns,
        model: d3.model,
        wire: wireToBridge(ns, m2.wire),
        ad
      })
      expect(d2.ok).toBe(true)
      expect(d2.plaintext).toBe(bytesToHex(utf8ToBytes('exchange m2')))
      model = d2.model

      // py -> TS twice, delivered out of order on our side
      const r2 = py({
        op: 'dr_encrypt',
        profile: ns,
        model,
        plaintext: bytesToHex(utf8ToBytes('exchange r2')),
        ad: adForSender(ns, 'passive', ad)
      })
      const r3 = py({
        op: 'dr_encrypt',
        profile: ns,
        model: r2.model,
        plaintext: bytesToHex(utf8ToBytes('exchange r3')),
        ad: adForSender(ns, 'passive', ad)
      })
      expect(r3.ok).toBe(true)
      expectBytes(
        session.decrypt(hex((r3.wire as { ciphertext: string }).ciphertext)),
        bytesToHex(utf8ToBytes('exchange r3'))
      )
      expect(session.state.skipped.length).toBeGreaterThan(0)
      expectBytes(
        session.decrypt(hex((r2.wire as { ciphertext: string }).ciphertext)),
        bytesToHex(utf8ToBytes('exchange r2'))
      )
    })
  }
})

describe.skipIf(!HAS_PYTHON)('full message interop through the bridge', () => {
  for (const ns of ['omemo2', 'legacy'] as const) {
    const x3dh = vectors.x3dh[ns]
    const dr = vectors.ratchet[ns]

    it(
      `${ns}: our encrypted elements decrypt under the reference stack`,
      { timeout: 120_000 },
      async () => {
        const bundle = pyBundle(ns)
        const alice = await managerFor(ns, x3dh.identityA, ALICE_JID, ALICE_DEVICE)

        // first message: key exchange wrapped key material plus payload
        const pt1 = envelope(ns, 'interop one')
        const e1 = serializeEncrypted(
          await alice.encrypt({
            recipients: [{ jid: BOB_JID, deviceId: BOB_DEVICE, bundle: bundle.parsed }],
            plaintext: pt1
          })
        )
        const d1 = py({
          op: 'msg_decrypt',
          profile: ns,
          xml: e1,
          deviceId: BOB_DEVICE,
          ownJid: BOB_JID,
          senderJid: ALICE_JID,
          x3dh: {
            ikPriv: x3dh.identityB.priv,
            spkPriv: x3dh.signedPreKey.priv,
            pkPriv: x3dh.preKey.priv,
            ikSignBit: signBitOf(x3dh.identityA),
            ratchetPriv: dr.bobRatchet.priv
          }
        })
        expect(d1.ok).toBe(true)
        expect(d1.wasKex).toBe(true)
        expect(d1.plaintext).toBe(bytesToHex(pt1))
        const ad = d1.ad as string
        let model = d1.model

        // the reference side replies; decrypting its message confirms our
        // session so follow-ups no longer carry the key exchange
        const reply1 = envelope(ns, 'reference reply one')
        const r1 = py({
          op: 'msg_encrypt',
          profile: ns,
          plaintext: bytesToHex(reply1),
          senderJid: BOB_JID,
          sid: BOB_DEVICE,
          recipientJid: ALICE_JID,
          rid: ALICE_DEVICE,
          session: { model, ad: adForSender(ns, 'passive', ad) }
        })
        expect(r1.ok).toBe(true)
        model = r1.model
        const a1 = await alice.decrypt(parseXml(r1.xml as string), BOB_JID)
        expect(bytesToHex(a1.plaintext ?? new Uint8Array(0))).toBe(bytesToHex(reply1))

        // follow-up message on the established session
        const pt2 = envelope(ns, 'interop two')
        const e2 = serializeEncrypted(
          await alice.encrypt({
            recipients: [{ jid: BOB_JID, deviceId: BOB_DEVICE }],
            plaintext: pt2
          })
        )
        const d2 = py({
          op: 'msg_decrypt',
          profile: ns,
          xml: e2,
          deviceId: BOB_DEVICE,
          ownJid: BOB_JID,
          senderJid: ALICE_JID,
          session: { model, ad }
        })
        expect(d2.ok).toBe(true)
        expect(d2.wasKex).toBe(false)
        expect(d2.plaintext).toBe(bytesToHex(pt2))
        model = d2.model

        // two more delivered out of order: the reference side must stash the
        // skipped message key and still decrypt both
        const pt3 = envelope(ns, 'interop three')
        const pt4 = envelope(ns, 'interop four')
        const e3 = serializeEncrypted(
          await alice.encrypt({
            recipients: [{ jid: BOB_JID, deviceId: BOB_DEVICE }],
            plaintext: pt3
          })
        )
        const e4 = serializeEncrypted(
          await alice.encrypt({
            recipients: [{ jid: BOB_JID, deviceId: BOB_DEVICE }],
            plaintext: pt4
          })
        )
        const d4 = py({
          op: 'msg_decrypt',
          profile: ns,
          xml: e4,
          deviceId: BOB_DEVICE,
          ownJid: BOB_JID,
          senderJid: ALICE_JID,
          session: { model, ad }
        })
        expect(d4.ok).toBe(true)
        expect(d4.plaintext).toBe(bytesToHex(pt4))
        const d3 = py({
          op: 'msg_decrypt',
          profile: ns,
          xml: e3,
          deviceId: BOB_DEVICE,
          ownJid: BOB_JID,
          senderJid: ALICE_JID,
          session: { model: d4.model, ad }
        })
        expect(d3.ok).toBe(true)
        expect(d3.plaintext).toBe(bytesToHex(pt3))
        model = d3.model

        // the reference side replies on the same session
        const reply = envelope(ns, 'reference reply')
        const enc = py({
          op: 'msg_encrypt',
          profile: ns,
          plaintext: bytesToHex(reply),
          senderJid: BOB_JID,
          sid: BOB_DEVICE,
          recipientJid: ALICE_JID,
          rid: ALICE_DEVICE,
          session: { model, ad: adForSender(ns, 'passive', ad) }
        })
        expect(enc.ok).toBe(true)
        const result = await alice.decrypt(parseXml(enc.xml as string), BOB_JID)
        expect(result.empty).toBe(false)
        expect(result.wasKeyExchange).toBe(false)
        expect(bytesToHex(result.plaintext ?? new Uint8Array(0))).toBe(bytesToHex(reply))
      }
    )

    it(`${ns}: reference encrypted elements decrypt on our side`, { timeout: 60_000 }, async () => {
      // our responder with vector key material so the reference initiates
      // against a bundle we can verify end to end
      const store = new InMemoryOmemoStore()
      await store.putIdentity(identityMaterial(ns, x3dh.identityB))
      await store.putSignedPreKey({
        id: x3dh.signedPreKey.id,
        pair: {
          privateKey: hex(x3dh.signedPreKey.priv),
          publicKey: hex(x3dh.signedPreKey.pub)
        },
        signature:
          ns === 'omemo2'
            ? ed25519.sign(hex(x3dh.signedPreKey.pub), hex(x3dh.identityB.seed))
            : xed25519Sign(
                hex(x3dh.identityB.priv),
                encodeCurveKeyWire(hex(x3dh.signedPreKey.pub))
              ),
        createdAt: 0
      })
      await store.putPreKey(x3dh.preKey.id, {
        privateKey: hex(x3dh.preKey.priv),
        publicKey: hex(x3dh.preKey.pub)
      })
      const bob = await OmemoManager.create({
        namespace: ns,
        store,
        ownJid: BOB_JID,
        deviceId: BOB_DEVICE,
        preKeyCount: 1
      })
      const bundleXml = serializeXml(await bob.buildBundle())

      // the reference initiates: X3DH against our bundle (verifying our
      // signed pre key signature), ratchet encrypt, serialize the element
      const pt1 = envelope(ns, 'reference hello')
      const e1 = py({
        op: 'msg_encrypt',
        profile: ns,
        plaintext: bytesToHex(pt1),
        senderJid: ALICE_JID,
        sid: ALICE_DEVICE,
        recipientJid: BOB_JID,
        rid: BOB_DEVICE,
        x3dh: {
          ikPriv: x3dh.identityA.priv,
          bundleXml,
          bundleJid: BOB_JID,
          bundleDeviceId: BOB_DEVICE,
          ekPriv: x3dh.ephemeral.priv,
          ratchetPriv: dr.aliceRatchet.priv
        }
      })
      expect(e1.ok).toBe(true)
      // fixed ephemeral key: the derived secret matches the golden vector
      expect(e1.sharedSecret).toBe(x3dh.sharedSecret)

      const d1 = await bob.decrypt(parseXml(e1.xml as string), ALICE_JID)
      expect(d1.wasKeyExchange).toBe(true)
      expect(bytesToHex(d1.plaintext ?? new Uint8Array(0))).toBe(bytesToHex(pt1))
      expect(d1.senderIdentityKey).toEqual(wireIdentity(ns, x3dh.identityA))

      // our reply decrypts on the reference side
      const pt2 = envelope(ns, 'our reply')
      const e2 = serializeEncrypted(
        await bob.encrypt({
          recipients: [{ jid: ALICE_JID, deviceId: ALICE_DEVICE }],
          plaintext: pt2
        })
      )
      const d2 = py({
        op: 'msg_decrypt',
        profile: ns,
        xml: e2,
        deviceId: ALICE_DEVICE,
        ownJid: ALICE_JID,
        senderJid: BOB_JID,
        session: {
          model: e1.model,
          ad: adForSender(ns, 'passive', e1.associatedData as string)
        }
      })
      expect(d2.ok).toBe(true)
      expect(d2.plaintext).toBe(bytesToHex(pt2))
    })
  }
})

describe.skipIf(!HAS_PYTHON)('bundle interop through the bridge', () => {
  for (const ns of ['omemo2', 'legacy'] as const) {
    const x3dh = vectors.x3dh[ns]

    it(
      `${ns}: reference-serialized bundle parses and verifies on our side`,
      { timeout: 30_000 },
      () => {
        const { parsed } = pyBundle(ns)
        expect(parsed.namespace).toBe(ns)
        expect(parsed.signedPreKeyId).toBe(x3dh.signedPreKey.id)
        expectBytes(parsed.signedPreKey, x3dh.signedPreKey.pub)
        expectBytes(parsed.identityKeyEd, x3dh.identityB.edPub)
        expectBytes(parsed.identityKeyCurve, x3dh.identityB.curvePub)
        expect(parsed.preKeys.map((p) => p.pkId)).toEqual([x3dh.preKey.id])
        expectBytes(parsed.preKeys[0]?.pk ?? new Uint8Array(0), x3dh.preKey.pub)
      }
    )

    it(`${ns}: our serialized bundle parses under the reference stack`, { timeout: 30_000 }, () => {
      const res = py({
        op: 'bundle_parse',
        profile: ns,
        xml: serializeBundle(ownBundle(ns)),
        jid: BOB_JID,
        deviceId: BOB_DEVICE
      })
      expect(res.ok).toBe(true)
      // the reference parser reports the identity key in Ed25519 form
      expect(res.identityKey).toBe(x3dh.identityB.edPub)
      expect(res.signedPreKey).toBe(x3dh.signedPreKey.pub)
      expect(res.signedPreKeyId).toBe(x3dh.signedPreKey.id)
      const preKeys = res.preKeys as Record<string, number>
      expect(preKeys[x3dh.preKey.pub]).toBe(x3dh.preKey.id)
      // the reference-side signature check already ran during parse; the
      // returned signature has the smuggled bit stripped for legacy
      const sig = hex(res.signedPreKeySignature as string)
      expect(sig.length).toBe(64)
      expect((sig[63] ?? 0) >> 7).toBe(0)
    })
  }
})
