// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​a​d​i​n​a​g​e
	 */
	appName: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	signIn: string
	/**
	 * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​X​M​P​P​ ​a​c​c​o​u​n​t
	 */
	signInTitle: string
	/**
	 * X​M​P​P​ ​a​d​d​r​e​s​s
	 */
	jid: string
	/**
	 * y​o​u​@​e​x​a​m​p​l​e​.​o​r​g
	 */
	jidPlaceholder: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	password: string
	/**
	 * S​e​r​v​e​r
	 */
	server: string
	/**
	 * w​s​s​:​/​/​e​x​a​m​p​l​e​.​o​r​g​/​x​m​p​p​-​w​e​b​s​o​c​k​e​t
	 */
	serverPlaceholder: string
	/**
	 * L​e​a​v​e​ ​e​m​p​t​y​ ​t​o​ ​d​i​s​c​o​v​e​r​ ​t​h​e​ ​s​e​r​v​e​r​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
	 */
	serverHint: string
	/**
	 * K​e​e​p​ ​m​e​ ​s​i​g​n​e​d​ ​i​n​ ​u​n​t​i​l​ ​I​ ​c​l​o​s​e​ ​t​h​i​s​ ​t​a​b
	 */
	rememberSession: string
	/**
	 * C​o​n​n​e​c​t
	 */
	connect: string
	/**
	 * C​o​n​n​e​c​t​i​n​g
	 */
	connecting: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
	 */
	authFailed: string
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​r​e​a​c​h​ ​t​h​e​ ​s​e​r​v​e​r
	 */
	connectionError: string
	/**
	 * C​o​n​v​e​r​s​a​t​i​o​n​s
	 */
	conversations: string
	/**
	 * C​o​n​t​a​c​t​s
	 */
	contacts: string
	/**
	 * A​d​d​ ​a​c​c​o​u​n​t
	 */
	addAccount: string
	/**
	 * R​e​m​o​v​e​ ​a​c​c​o​u​n​t
	 */
	removeAccount: string
	/**
	 * o​n​l​i​n​e
	 */
	online: string
	/**
	 * o​f​f​l​i​n​e
	 */
	offline: string
	/**
	 * a​w​a​y
	 */
	away: string
	/**
	 * b​u​s​y
	 */
	busy: string
	/**
	 * M​e​s​s​a​g​e​ ​{​p​e​e​r​}
	 * @param {string} peer
	 */
	messagePlaceholder: RequiredParams<'peer'>
	/**
	 * S​e​n​d
	 */
	send: string
	/**
	 * S​e​l​e​c​t​ ​a​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​o​r​ ​c​o​n​t​a​c​t​ ​t​o​ ​s​t​a​r​t​ ​c​h​a​t​t​i​n​g
	 */
	noConversation: string
	/**
	 * N​o​ ​c​o​n​t​a​c​t​s​ ​y​e​t
	 */
	emptyRoster: string
	/**
	 * T​o​g​g​l​e​ ​t​h​e​m​e
	 */
	toggleTheme: string
	/**
	 * B​a​c​k
	 */
	back: string
	/**
	 * E​n​c​r​y​p​t​e​d
	 */
	encrypted: string
	/**
	 * N​o​t​ ​e​n​c​r​y​p​t​e​d
	 */
	notEncrypted: string
	/**
	 * {​c​o​u​n​t​}​ ​u​n​r​e​a​d
	 * @param {number} count
	 */
	unread: RequiredParams<'count'>
	/**
	 * t​y​p​i​n​g​…
	 */
	typing: string
	/**
	 * {​n​a​m​e​}​ ​i​s​ ​t​y​p​i​n​g​…
	 * @param {string} name
	 */
	typingNick: RequiredParams<'name'>
	/**
	 * T​r​y​ ​t​h​e​ ​d​e​m​o
	 */
	tryDemo: string
	/**
	 * N​o​ ​s​e​r​v​e​r​ ​n​e​e​d​e​d​.​ ​F​a​k​e​ ​c​o​n​t​a​c​t​s​,​ ​f​a​k​e​ ​c​h​a​t​s​,​ ​a​l​l​ ​l​o​c​a​l​.
	 */
	demoHint: string
	/**
	 * R​o​o​m​s
	 */
	rooms: string
	/**
	 * J​o​i​n​ ​a​ ​r​o​o​m
	 */
	joinRoom: string
	/**
	 * R​o​o​m​ ​a​d​d​r​e​s​s
	 */
	roomJid: string
	/**
	 * r​o​o​m​@​c​o​n​f​e​r​e​n​c​e​.​e​x​a​m​p​l​e​.​o​r​g
	 */
	roomJidPlaceholder: string
	/**
	 * N​i​c​k​n​a​m​e
	 */
	nickname: string
	/**
	 * y​o​u​r​ ​n​i​c​k​n​a​m​e​ ​i​n​ ​t​h​e​ ​r​o​o​m
	 */
	nicknamePlaceholder: string
	/**
	 * J​o​i​n
	 */
	join: string
	/**
	 * L​e​a​v​e​ ​r​o​o​m
	 */
	leaveRoom: string
	/**
	 * {​c​o​u​n​t​}​ ​o​c​c​u​p​a​n​t​s
	 * @param {number} count
	 */
	occupants: RequiredParams<'count'>
	/**
	 * R​o​o​m​ ​s​u​b​j​e​c​t
	 */
	roomSubject: string
	/**
	 * A​d​d​ ​a​ ​c​o​n​t​a​c​t
	 */
	addContact: string
	/**
	 * C​o​n​t​a​c​t​ ​a​d​d​r​e​s​s
	 */
	contactJid: string
	/**
	 * D​i​s​p​l​a​y​ ​n​a​m​e
	 */
	contactName: string
	/**
	 * A​d​d
	 */
	add: string
	/**
	 * S​u​b​s​c​r​i​p​t​i​o​n​ ​r​e​q​u​e​s​t​s
	 */
	subscriptionRequests: string
	/**
	 * {​f​r​o​m​}​ ​w​a​n​t​s​ ​t​o​ ​s​e​e​ ​y​o​u​r​ ​p​r​e​s​e​n​c​e
	 * @param {string} from
	 */
	wantsToSubscribe: RequiredParams<'from'>
	/**
	 * A​c​c​e​p​t
	 */
	accept: string
	/**
	 * D​e​n​y
	 */
	deny: string
	/**
	 * D​e​l​i​v​e​r​e​d
	 */
	delivered: string
	/**
	 * R​e​a​d
	 */
	read: string
	/**
	 * S​e​n​t
	 */
	sent: string
	/**
	 * S​e​a​r​c​h​ ​c​o​n​v​e​r​s​a​t​i​o​n​s​ ​a​n​d​ ​c​o​n​t​a​c​t​s
	 */
	search: string
	/**
	 * E​x​p​a​n​d​ ​s​e​c​t​i​o​n
	 */
	expandSection: string
	/**
	 * C​o​l​l​a​p​s​e​ ​s​e​c​t​i​o​n
	 */
	collapseSection: string
	/**
	 * R​e​p​l​y
	 */
	reply: string
	/**
	 * R​e​p​l​y​i​n​g​ ​t​o​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	replyingTo: RequiredParams<'name'>
	/**
	 * E​d​i​t​ ​m​e​s​s​a​g​e
	 */
	editMessage: string
	/**
	 * E​d​i​t​i​n​g​ ​m​e​s​s​a​g​e
	 */
	editingMessage: string
	/**
	 * e​d​i​t​e​d
	 */
	edited: string
	/**
	 * A​d​d​ ​r​e​a​c​t​i​o​n
	 */
	react: string
	/**
	 * C​o​p​y​ ​m​e​s​s​a​g​e​ ​t​e​x​t
	 */
	copyMessage: string
	/**
	 * A​t​t​a​c​h​ ​f​i​l​e
	 */
	attachFile: string
	/**
	 * R​e​c​o​r​d​ ​v​o​i​c​e​ ​m​e​s​s​a​g​e
	 */
	recordVoice: string
	/**
	 * S​t​o​p​ ​a​n​d​ ​s​e​n​d
	 */
	stopRecording: string
	/**
	 * C​a​n​c​e​l​ ​r​e​c​o​r​d​i​n​g
	 */
	cancelRecording: string
	/**
	 * V​o​i​c​e​ ​m​e​s​s​a​g​e
	 */
	voiceMessage: string
	/**
	 * I​m​a​g​e​ ​a​t​t​a​c​h​m​e​n​t
	 */
	imageAttachment: string
	/**
	 * F​i​l​e​ ​a​t​t​a​c​h​m​e​n​t
	 */
	fileAttachment: string
	/**
	 * U​p​l​o​a​d​ ​f​a​i​l​e​d
	 */
	uploadFailed: string
	/**
	 * S​i​g​n​e​d
	 */
	signed: string
	/**
	 * V​e​r​i​f​i​e​d​ ​s​e​n​d​e​r
	 */
	verified: string
	/**
	 * C​a​n​c​e​l
	 */
	cancelEdit: string
	/**
	 * Y​o​u
	 */
	you: string
	/**
	 * P​r​i​v​a​c​y
	 */
	privacy: string
	/**
	 * S​e​n​d​ ​t​y​p​i​n​g​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
	 */
	sendTyping: string
	/**
	 * S​e​n​d​ ​d​e​l​i​v​e​r​y​ ​r​e​c​e​i​p​t​s
	 */
	sendReceipts: string
	/**
	 * S​e​n​d​ ​r​e​a​d​ ​m​a​r​k​e​r​s
	 */
	sendReadMarkers: string
	/**
	 * S​p​l​i​t​ ​v​i​e​w
	 */
	splitView: string
	/**
	 * C​l​o​s​e​ ​p​a​n​e
	 */
	closePane: string
	/**
	 * O​p​e​n​ ​i​n​ ​s​p​l​i​t​ ​v​i​e​w
	 */
	openInSplit: string
	/**
	 * C​h​o​o​s​e​ ​a​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	pickConversation: string
	/**
	 * P​l​a​y
	 */
	play: string
	/**
	 * P​a​u​s​e
	 */
	pause: string
	/**
	 * P​i​c​k​ ​a​n​ ​e​m​o​j​i
	 */
	addReactionEmoji: string
	/**
	 * M​e​s​s​a​g​e​ ​s​i​g​n​e​d
	 */
	messageSigned: string
	/**
	 * L​o​a​d​ ​o​l​d​e​r​ ​m​e​s​s​a​g​e​s
	 */
	loadOlder: string
	/**
	 * B​e​g​i​n​n​i​n​g​ ​o​f​ ​t​h​e​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	beginningOfHistory: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * P​r​e​f​e​r​e​n​c​e​s​ ​a​r​e​ ​s​t​o​r​e​d​ ​o​n​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​o​n​l​y
	 */
	settingsHint: string
	/**
	 * G​e​n​e​r​a​l
	 */
	general: string
	/**
	 * S​e​n​d​ ​m​e​s​s​a​g​e​s​ ​w​i​t​h​ ​E​n​t​e​r
	 */
	sendWithEnter: string
	/**
	 * D​e​s​k​t​o​p​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
	 */
	notifications: string
	/**
	 * N​o​t​i​f​i​c​a​t​i​o​n​ ​s​o​u​n​d​s
	 */
	sounds: string
	/**
	 * K​e​y​b​o​a​r​d​ ​s​h​o​r​t​c​u​t​s
	 */
	keyboard: string
	/**
	 * C​l​i​c​k​ ​a​ ​s​h​o​r​t​c​u​t​ ​t​o​ ​r​e​b​i​n​d​ ​i​t​.​ ​P​r​e​s​s​ ​E​s​c​a​p​e​ ​t​o​ ​c​a​n​c​e​l​.
	 */
	keyboardHint: string
	/**
	 * p​r​e​s​s​ ​k​e​y​s
	 */
	pressKeys: string
	/**
	 * R​e​b​i​n​d​ ​{​a​c​t​i​o​n​}
	 * @param {string} action
	 */
	rebindFor: RequiredParams<'action'>
	/**
	 * R​e​s​e​t​ ​t​o​ ​d​e​f​a​u​l​t
	 */
	resetBinding: string
	/**
	 * O​p​e​n​ ​s​e​t​t​i​n​g​s
	 */
	kbSettings: string
	/**
	 * T​o​g​g​l​e​ ​t​h​e​m​e
	 */
	kbToggleTheme: string
	/**
	 * N​e​x​t​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	kbNextConversation: string
	/**
	 * P​r​e​v​i​o​u​s​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	kbPrevConversation: string
	/**
	 * C​l​o​s​e​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	kbCloseConversation: string
	/**
	 * F​o​c​u​s​ ​m​e​s​s​a​g​e​ ​i​n​p​u​t
	 */
	kbFocusComposer: string
	/**
	 * S​w​i​t​c​h​ ​t​o​ ​a​c​c​o​u​n​t​ ​{​n​}
	 * @param {number} n
	 */
	kbAccount: RequiredParams<'n'>
	/**
	 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	crashTitle: string
	/**
	 * T​h​e​ ​a​p​p​ ​h​i​t​ ​a​n​ ​u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​.​ ​Y​o​u​r​ ​m​e​s​s​a​g​e​s​ ​a​r​e​ ​s​t​o​r​e​d​ ​l​o​c​a​l​l​y​ ​a​n​d​ ​n​o​t​h​i​n​g​ ​w​a​s​ ​s​e​n​t​ ​a​n​y​w​h​e​r​e​.
	 */
	crashDescription: string
	/**
	 * T​r​y​ ​a​g​a​i​n
	 */
	crashRetry: string
	/**
	 * R​e​l​o​a​d​ ​a​p​p
	 */
	crashReload: string
	/**
	 * C​o​p​y​ ​e​r​r​o​r
	 */
	copyError: string
	/**
	 * C​o​p​i​e​d
	 */
	copied: string
	/**
	 * C​o​n​n​e​c​t​e​d​ ​a​s​ ​{​j​i​d​}
	 * @param {string} jid
	 */
	toastConnected: RequiredParams<'jid'>
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​p​r​o​b​l​e​m​ ​f​o​r​ ​{​j​i​d​}
	 * @param {string} jid
	 */
	toastConnectionError: RequiredParams<'jid'>
	/**
	 * D​i​s​c​o​n​n​e​c​t​e​d​:​ ​{​j​i​d​}
	 * @param {string} jid
	 */
	toastDisconnected: RequiredParams<'jid'>
	/**
	 * R​e​m​o​v​e​ ​t​h​i​s​ ​a​c​c​o​u​n​t​?
	 */
	removeAccountTitle: string
	/**
	 * {​j​i​d​}​ ​w​i​l​l​ ​b​e​ ​d​i​s​c​o​n​n​e​c​t​e​d​ ​a​n​d​ ​i​t​s​ ​l​o​c​a​l​ ​d​a​t​a​ ​o​n​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​d​e​l​e​t​e​d​.​ ​T​h​e​ ​a​c​c​o​u​n​t​ ​i​t​s​e​l​f​ ​s​t​a​y​s​ ​o​n​ ​t​h​e​ ​s​e​r​v​e​r​.
	 * @param {string} jid
	 */
	removeAccountDescription: RequiredParams<'jid'>
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * R​e​m​o​v​e
	 */
	confirm: string
	/**
	 * m​o​d
	 */
	roleModerator: string
	/**
	 * a​d​m​i​n
	 */
	roleAdmin: string
	/**
	 * O​p​e​n​ ​s​e​t​t​i​n​g​s
	 */
	openSettings: string
	/**
	 * L​o​a​d​i​n​g​ ​c​o​n​t​a​c​t​s
	 */
	loadingContacts: string
	/**
	 * C​o​n​n​e​c​t​i​n​g​ ​t​o​ ​t​h​e​ ​s​e​r​v​e​r
	 */
	connectingStatus: string
	/**
	 * D​a​n​g​e​r​ ​z​o​n​e
	 */
	dangerZone: string
	/**
	 * W​i​p​e​ ​l​o​c​a​l​ ​d​a​t​a
	 */
	wipeData: string
	/**
	 * D​e​l​e​t​e​ ​a​l​l​ ​l​o​c​a​l​ ​m​e​s​s​a​g​e​s​,​ ​k​e​y​s​ ​a​n​d​ ​s​e​t​t​i​n​g​s​ ​o​n​ ​t​h​i​s​ ​d​e​v​i​c​e
	 */
	wipeDataHint: string
	/**
	 * W​i​p​e​ ​a​l​l​ ​l​o​c​a​l​ ​d​a​t​a​?
	 */
	wipeDataTitle: string
	/**
	 * E​v​e​r​y​ ​a​c​c​o​u​n​t​ ​s​e​s​s​i​o​n​,​ ​c​a​c​h​e​d​ ​m​e​s​s​a​g​e​ ​a​n​d​ ​s​t​o​r​e​d​ ​k​e​y​ ​o​n​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​w​i​l​l​ ​b​e​ ​d​e​l​e​t​e​d​.​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
	 */
	wipeDataDescription: string
}

export type TranslationFunctions = {
	/**
	 * Badinage
	 */
	appName: () => LocalizedString
	/**
	 * Sign in
	 */
	signIn: () => LocalizedString
	/**
	 * Sign in to your XMPP account
	 */
	signInTitle: () => LocalizedString
	/**
	 * XMPP address
	 */
	jid: () => LocalizedString
	/**
	 * you@example.org
	 */
	jidPlaceholder: () => LocalizedString
	/**
	 * Password
	 */
	password: () => LocalizedString
	/**
	 * Server
	 */
	server: () => LocalizedString
	/**
	 * wss://example.org/xmpp-websocket
	 */
	serverPlaceholder: () => LocalizedString
	/**
	 * Leave empty to discover the server automatically
	 */
	serverHint: () => LocalizedString
	/**
	 * Keep me signed in until I close this tab
	 */
	rememberSession: () => LocalizedString
	/**
	 * Connect
	 */
	connect: () => LocalizedString
	/**
	 * Connecting
	 */
	connecting: () => LocalizedString
	/**
	 * Authentication failed
	 */
	authFailed: () => LocalizedString
	/**
	 * Could not reach the server
	 */
	connectionError: () => LocalizedString
	/**
	 * Conversations
	 */
	conversations: () => LocalizedString
	/**
	 * Contacts
	 */
	contacts: () => LocalizedString
	/**
	 * Add account
	 */
	addAccount: () => LocalizedString
	/**
	 * Remove account
	 */
	removeAccount: () => LocalizedString
	/**
	 * online
	 */
	online: () => LocalizedString
	/**
	 * offline
	 */
	offline: () => LocalizedString
	/**
	 * away
	 */
	away: () => LocalizedString
	/**
	 * busy
	 */
	busy: () => LocalizedString
	/**
	 * Message {peer}
	 */
	messagePlaceholder: (arg: { peer: string }) => LocalizedString
	/**
	 * Send
	 */
	send: () => LocalizedString
	/**
	 * Select a conversation or contact to start chatting
	 */
	noConversation: () => LocalizedString
	/**
	 * No contacts yet
	 */
	emptyRoster: () => LocalizedString
	/**
	 * Toggle theme
	 */
	toggleTheme: () => LocalizedString
	/**
	 * Back
	 */
	back: () => LocalizedString
	/**
	 * Encrypted
	 */
	encrypted: () => LocalizedString
	/**
	 * Not encrypted
	 */
	notEncrypted: () => LocalizedString
	/**
	 * {count} unread
	 */
	unread: (arg: { count: number }) => LocalizedString
	/**
	 * typing…
	 */
	typing: () => LocalizedString
	/**
	 * {name} is typing…
	 */
	typingNick: (arg: { name: string }) => LocalizedString
	/**
	 * Try the demo
	 */
	tryDemo: () => LocalizedString
	/**
	 * No server needed. Fake contacts, fake chats, all local.
	 */
	demoHint: () => LocalizedString
	/**
	 * Rooms
	 */
	rooms: () => LocalizedString
	/**
	 * Join a room
	 */
	joinRoom: () => LocalizedString
	/**
	 * Room address
	 */
	roomJid: () => LocalizedString
	/**
	 * room@conference.example.org
	 */
	roomJidPlaceholder: () => LocalizedString
	/**
	 * Nickname
	 */
	nickname: () => LocalizedString
	/**
	 * your nickname in the room
	 */
	nicknamePlaceholder: () => LocalizedString
	/**
	 * Join
	 */
	join: () => LocalizedString
	/**
	 * Leave room
	 */
	leaveRoom: () => LocalizedString
	/**
	 * {count} occupants
	 */
	occupants: (arg: { count: number }) => LocalizedString
	/**
	 * Room subject
	 */
	roomSubject: () => LocalizedString
	/**
	 * Add a contact
	 */
	addContact: () => LocalizedString
	/**
	 * Contact address
	 */
	contactJid: () => LocalizedString
	/**
	 * Display name
	 */
	contactName: () => LocalizedString
	/**
	 * Add
	 */
	add: () => LocalizedString
	/**
	 * Subscription requests
	 */
	subscriptionRequests: () => LocalizedString
	/**
	 * {from} wants to see your presence
	 */
	wantsToSubscribe: (arg: { from: string }) => LocalizedString
	/**
	 * Accept
	 */
	accept: () => LocalizedString
	/**
	 * Deny
	 */
	deny: () => LocalizedString
	/**
	 * Delivered
	 */
	delivered: () => LocalizedString
	/**
	 * Read
	 */
	read: () => LocalizedString
	/**
	 * Sent
	 */
	sent: () => LocalizedString
	/**
	 * Search conversations and contacts
	 */
	search: () => LocalizedString
	/**
	 * Expand section
	 */
	expandSection: () => LocalizedString
	/**
	 * Collapse section
	 */
	collapseSection: () => LocalizedString
	/**
	 * Reply
	 */
	reply: () => LocalizedString
	/**
	 * Replying to {name}
	 */
	replyingTo: (arg: { name: string }) => LocalizedString
	/**
	 * Edit message
	 */
	editMessage: () => LocalizedString
	/**
	 * Editing message
	 */
	editingMessage: () => LocalizedString
	/**
	 * edited
	 */
	edited: () => LocalizedString
	/**
	 * Add reaction
	 */
	react: () => LocalizedString
	/**
	 * Copy message text
	 */
	copyMessage: () => LocalizedString
	/**
	 * Attach file
	 */
	attachFile: () => LocalizedString
	/**
	 * Record voice message
	 */
	recordVoice: () => LocalizedString
	/**
	 * Stop and send
	 */
	stopRecording: () => LocalizedString
	/**
	 * Cancel recording
	 */
	cancelRecording: () => LocalizedString
	/**
	 * Voice message
	 */
	voiceMessage: () => LocalizedString
	/**
	 * Image attachment
	 */
	imageAttachment: () => LocalizedString
	/**
	 * File attachment
	 */
	fileAttachment: () => LocalizedString
	/**
	 * Upload failed
	 */
	uploadFailed: () => LocalizedString
	/**
	 * Signed
	 */
	signed: () => LocalizedString
	/**
	 * Verified sender
	 */
	verified: () => LocalizedString
	/**
	 * Cancel
	 */
	cancelEdit: () => LocalizedString
	/**
	 * You
	 */
	you: () => LocalizedString
	/**
	 * Privacy
	 */
	privacy: () => LocalizedString
	/**
	 * Send typing notifications
	 */
	sendTyping: () => LocalizedString
	/**
	 * Send delivery receipts
	 */
	sendReceipts: () => LocalizedString
	/**
	 * Send read markers
	 */
	sendReadMarkers: () => LocalizedString
	/**
	 * Split view
	 */
	splitView: () => LocalizedString
	/**
	 * Close pane
	 */
	closePane: () => LocalizedString
	/**
	 * Open in split view
	 */
	openInSplit: () => LocalizedString
	/**
	 * Choose a conversation
	 */
	pickConversation: () => LocalizedString
	/**
	 * Play
	 */
	play: () => LocalizedString
	/**
	 * Pause
	 */
	pause: () => LocalizedString
	/**
	 * Pick an emoji
	 */
	addReactionEmoji: () => LocalizedString
	/**
	 * Message signed
	 */
	messageSigned: () => LocalizedString
	/**
	 * Load older messages
	 */
	loadOlder: () => LocalizedString
	/**
	 * Beginning of the conversation
	 */
	beginningOfHistory: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * Preferences are stored on this device only
	 */
	settingsHint: () => LocalizedString
	/**
	 * General
	 */
	general: () => LocalizedString
	/**
	 * Send messages with Enter
	 */
	sendWithEnter: () => LocalizedString
	/**
	 * Desktop notifications
	 */
	notifications: () => LocalizedString
	/**
	 * Notification sounds
	 */
	sounds: () => LocalizedString
	/**
	 * Keyboard shortcuts
	 */
	keyboard: () => LocalizedString
	/**
	 * Click a shortcut to rebind it. Press Escape to cancel.
	 */
	keyboardHint: () => LocalizedString
	/**
	 * press keys
	 */
	pressKeys: () => LocalizedString
	/**
	 * Rebind {action}
	 */
	rebindFor: (arg: { action: string }) => LocalizedString
	/**
	 * Reset to default
	 */
	resetBinding: () => LocalizedString
	/**
	 * Open settings
	 */
	kbSettings: () => LocalizedString
	/**
	 * Toggle theme
	 */
	kbToggleTheme: () => LocalizedString
	/**
	 * Next conversation
	 */
	kbNextConversation: () => LocalizedString
	/**
	 * Previous conversation
	 */
	kbPrevConversation: () => LocalizedString
	/**
	 * Close conversation
	 */
	kbCloseConversation: () => LocalizedString
	/**
	 * Focus message input
	 */
	kbFocusComposer: () => LocalizedString
	/**
	 * Switch to account {n}
	 */
	kbAccount: (arg: { n: number }) => LocalizedString
	/**
	 * Something went wrong
	 */
	crashTitle: () => LocalizedString
	/**
	 * The app hit an unexpected error. Your messages are stored locally and nothing was sent anywhere.
	 */
	crashDescription: () => LocalizedString
	/**
	 * Try again
	 */
	crashRetry: () => LocalizedString
	/**
	 * Reload app
	 */
	crashReload: () => LocalizedString
	/**
	 * Copy error
	 */
	copyError: () => LocalizedString
	/**
	 * Copied
	 */
	copied: () => LocalizedString
	/**
	 * Connected as {jid}
	 */
	toastConnected: (arg: { jid: string }) => LocalizedString
	/**
	 * Connection problem for {jid}
	 */
	toastConnectionError: (arg: { jid: string }) => LocalizedString
	/**
	 * Disconnected: {jid}
	 */
	toastDisconnected: (arg: { jid: string }) => LocalizedString
	/**
	 * Remove this account?
	 */
	removeAccountTitle: () => LocalizedString
	/**
	 * {jid} will be disconnected and its local data on this device deleted. The account itself stays on the server.
	 */
	removeAccountDescription: (arg: { jid: string }) => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Remove
	 */
	confirm: () => LocalizedString
	/**
	 * mod
	 */
	roleModerator: () => LocalizedString
	/**
	 * admin
	 */
	roleAdmin: () => LocalizedString
	/**
	 * Open settings
	 */
	openSettings: () => LocalizedString
	/**
	 * Loading contacts
	 */
	loadingContacts: () => LocalizedString
	/**
	 * Connecting to the server
	 */
	connectingStatus: () => LocalizedString
	/**
	 * Danger zone
	 */
	dangerZone: () => LocalizedString
	/**
	 * Wipe local data
	 */
	wipeData: () => LocalizedString
	/**
	 * Delete all local messages, keys and settings on this device
	 */
	wipeDataHint: () => LocalizedString
	/**
	 * Wipe all local data?
	 */
	wipeDataTitle: () => LocalizedString
	/**
	 * Every account session, cached message and stored key on this device will be deleted. This cannot be undone.
	 */
	wipeDataDescription: () => LocalizedString
}

export type Formatters = {}
