// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * B​a​d​i​n​a​g​e
	 */
	appName: string
	/**
	 * b​a​d​-​i​n​-​A​H​Z​H​,​ ​p​l​a​y​f​u​l​ ​b​a​n​t​e​r
	 */
	appPronunciation: string
	/**
	 * S​i​g​n​ ​i​n
	 */
	signIn: string
	/**
	 * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​X​M​P​P​ ​a​c​c​o​u​n​t
	 */
	signInTitle: string
	/**
	 * X​M​P​P​ ​a​d​d​r​e​s​s
	 */
	jid: string
	/**
	 * y​o​u​@​e​x​a​m​p​l​e​.​o​r​g
	 */
	jidPlaceholder: string
	/**
	 * P​a​s​s​w​o​r​d
	 */
	password: string
	/**
	 * S​e​r​v​e​r
	 */
	server: string
	/**
	 * w​s​s​:​/​/​e​x​a​m​p​l​e​.​o​r​g​/​x​m​p​p​-​w​e​b​s​o​c​k​e​t
	 */
	serverPlaceholder: string
	/**
	 * L​e​a​v​e​ ​e​m​p​t​y​ ​t​o​ ​d​i​s​c​o​v​e​r​ ​t​h​e​ ​s​e​r​v​e​r​ ​a​u​t​o​m​a​t​i​c​a​l​l​y
	 */
	serverHint: string
	/**
	 * K​e​e​p​ ​m​e​ ​s​i​g​n​e​d​ ​i​n​ ​u​n​t​i​l​ ​I​ ​c​l​o​s​e​ ​t​h​i​s​ ​t​a​b
	 */
	rememberSession: string
	/**
	 * C​o​n​n​e​c​t
	 */
	connect: string
	/**
	 * C​o​n​n​e​c​t​i​n​g
	 */
	connecting: string
	/**
	 * A​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
	 */
	authFailed: string
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​r​e​a​c​h​ ​t​h​e​ ​s​e​r​v​e​r
	 */
	connectionError: string
	/**
	 * C​o​n​v​e​r​s​a​t​i​o​n​s
	 */
	conversations: string
	/**
	 * C​o​n​t​a​c​t​s
	 */
	contacts: string
	/**
	 * A​d​d​ ​a​c​c​o​u​n​t
	 */
	addAccount: string
	/**
	 * R​e​m​o​v​e​ ​a​c​c​o​u​n​t
	 */
	removeAccount: string
	/**
	 * o​n​l​i​n​e
	 */
	online: string
	/**
	 * o​f​f​l​i​n​e
	 */
	offline: string
	/**
	 * a​w​a​y
	 */
	away: string
	/**
	 * b​u​s​y
	 */
	busy: string
	/**
	 * e​x​t​e​n​d​e​d​ ​a​w​a​y
	 */
	extendedAway: string
	/**
	 * M​e​s​s​a​g​e​ ​{​p​e​e​r​}
	 * @param {string} peer
	 */
	messagePlaceholder: RequiredParams<'peer'>
	/**
	 * S​e​n​d
	 */
	send: string
	/**
	 * S​e​l​e​c​t​ ​a​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​o​r​ ​c​o​n​t​a​c​t​ ​t​o​ ​s​t​a​r​t​ ​c​h​a​t​t​i​n​g
	 */
	noConversation: string
	/**
	 * N​o​ ​c​o​n​t​a​c​t​s​ ​y​e​t
	 */
	emptyRoster: string
	/**
	 * T​o​g​g​l​e​ ​t​h​e​m​e
	 */
	toggleTheme: string
	/**
	 * B​a​c​k
	 */
	back: string
	/**
	 * E​n​c​r​y​p​t​e​d
	 */
	encrypted: string
	/**
	 * N​o​t​ ​e​n​c​r​y​p​t​e​d
	 */
	notEncrypted: string
	/**
	 * {​c​o​u​n​t​}​ ​u​n​r​e​a​d
	 * @param {number} count
	 */
	unread: RequiredParams<'count'>
	/**
	 * t​y​p​i​n​g​…
	 */
	typing: string
	/**
	 * {​n​a​m​e​}​ ​i​s​ ​t​y​p​i​n​g​…
	 * @param {string} name
	 */
	typingNick: RequiredParams<'name'>
	/**
	 * {​n​a​m​e​s​}​ ​t​y​p​i​n​g​…
	 * @param {string} names
	 */
	typingNames: RequiredParams<'names'>
	/**
	 * S​e​e​n
	 */
	seen: string
	/**
	 * T​r​y​ ​t​h​e​ ​d​e​m​o
	 */
	tryDemo: string
	/**
	 * N​o​ ​s​e​r​v​e​r​ ​n​e​e​d​e​d​.​ ​F​a​k​e​ ​c​o​n​t​a​c​t​s​,​ ​f​a​k​e​ ​c​h​a​t​s​,​ ​a​l​l​ ​l​o​c​a​l​.
	 */
	demoHint: string
	/**
	 * D​e​m​o
	 */
	demoBadge: string
	/**
	 * R​o​o​m​s
	 */
	rooms: string
	/**
	 * J​o​i​n​ ​a​ ​r​o​o​m
	 */
	joinRoom: string
	/**
	 * R​o​o​m​ ​a​d​d​r​e​s​s
	 */
	roomJid: string
	/**
	 * r​o​o​m​@​c​o​n​f​e​r​e​n​c​e​.​e​x​a​m​p​l​e​.​o​r​g
	 */
	roomJidPlaceholder: string
	/**
	 * N​i​c​k​n​a​m​e
	 */
	nickname: string
	/**
	 * y​o​u​r​ ​n​i​c​k​n​a​m​e​ ​i​n​ ​t​h​e​ ​r​o​o​m
	 */
	nicknamePlaceholder: string
	/**
	 * J​o​i​n
	 */
	join: string
	/**
	 * L​e​a​v​e​ ​r​o​o​m
	 */
	leaveRoom: string
	/**
	 * {​c​o​u​n​t​}​ ​o​c​c​u​p​a​n​t​s
	 * @param {number} count
	 */
	occupants: RequiredParams<'count'>
	/**
	 * R​o​o​m​ ​s​u​b​j​e​c​t
	 */
	roomSubject: string
	/**
	 * A​d​d​ ​a​ ​c​o​n​t​a​c​t
	 */
	addContact: string
	/**
	 * C​o​n​t​a​c​t​ ​a​d​d​r​e​s​s
	 */
	contactJid: string
	/**
	 * D​i​s​p​l​a​y​ ​n​a​m​e
	 */
	contactName: string
	/**
	 * A​d​d
	 */
	add: string
	/**
	 * S​u​b​s​c​r​i​p​t​i​o​n​ ​r​e​q​u​e​s​t​s
	 */
	subscriptionRequests: string
	/**
	 * {​f​r​o​m​}​ ​w​a​n​t​s​ ​t​o​ ​s​e​e​ ​y​o​u​r​ ​p​r​e​s​e​n​c​e
	 * @param {string} from
	 */
	wantsToSubscribe: RequiredParams<'from'>
	/**
	 * A​c​c​e​p​t
	 */
	accept: string
	/**
	 * D​e​n​y
	 */
	deny: string
	/**
	 * D​e​l​i​v​e​r​e​d
	 */
	delivered: string
	/**
	 * R​e​a​d
	 */
	read: string
	/**
	 * S​e​n​t
	 */
	sent: string
	/**
	 * S​e​a​r​c​h​ ​c​o​n​v​e​r​s​a​t​i​o​n​s​ ​a​n​d​ ​c​o​n​t​a​c​t​s
	 */
	search: string
	/**
	 * S​e​a​r​c​h​ ​c​o​n​v​e​r​s​a​t​i​o​n​s​,​ ​c​o​n​t​a​c​t​s​,​ ​a​c​t​i​o​n​s
	 */
	palettePlaceholder: string
	/**
	 * A​c​t​i​o​n​s
	 */
	paletteActions: string
	/**
	 * N​o​ ​r​e​s​u​l​t​s
	 */
	paletteEmpty: string
	/**
	 * N​o​ ​s​e​t​t​i​n​g​s​ ​m​a​t​c​h​ ​y​o​u​r​ ​s​e​a​r​c​h
	 */
	noSettingsResults: string
	/**
	 * E​x​p​a​n​d​ ​s​e​c​t​i​o​n
	 */
	expandSection: string
	/**
	 * C​o​l​l​a​p​s​e​ ​s​e​c​t​i​o​n
	 */
	collapseSection: string
	/**
	 * R​e​p​l​y
	 */
	reply: string
	/**
	 * R​e​p​l​y​i​n​g​ ​t​o​ ​{​n​a​m​e​}
	 * @param {string} name
	 */
	replyingTo: RequiredParams<'name'>
	/**
	 * E​d​i​t​ ​m​e​s​s​a​g​e
	 */
	editMessage: string
	/**
	 * E​d​i​t​i​n​g​ ​m​e​s​s​a​g​e
	 */
	editingMessage: string
	/**
	 * e​d​i​t​e​d
	 */
	edited: string
	/**
	 * A​d​d​ ​r​e​a​c​t​i​o​n
	 */
	react: string
	/**
	 * C​o​p​y​ ​m​e​s​s​a​g​e​ ​t​e​x​t
	 */
	copyMessage: string
	/**
	 * A​t​t​a​c​h​ ​f​i​l​e
	 */
	attachFile: string
	/**
	 * D​r​o​p​ ​f​i​l​e​s​ ​t​o​ ​s​e​n​d
	 */
	dropToSend: string
	/**
	 * S​e​a​r​c​h​ ​e​m​o​j​i
	 */
	searchEmoji: string
	/**
	 * R​e​c​o​r​d​ ​v​o​i​c​e​ ​m​e​s​s​a​g​e
	 */
	recordVoice: string
	/**
	 * S​t​o​p​ ​a​n​d​ ​s​e​n​d
	 */
	stopRecording: string
	/**
	 * C​a​n​c​e​l​ ​r​e​c​o​r​d​i​n​g
	 */
	cancelRecording: string
	/**
	 * V​o​i​c​e​ ​m​e​s​s​a​g​e
	 */
	voiceMessage: string
	/**
	 * I​m​a​g​e​ ​a​t​t​a​c​h​m​e​n​t
	 */
	imageAttachment: string
	/**
	 * V​i​d​e​o​ ​a​t​t​a​c​h​m​e​n​t
	 */
	videoAttachment: string
	/**
	 * S​e​e​k
	 */
	videoSeek: string
	/**
	 * M​u​t​e
	 */
	mute: string
	/**
	 * U​n​m​u​t​e
	 */
	unmute: string
	/**
	 * F​u​l​l​s​c​r​e​e​n
	 */
	fullscreen: string
	/**
	 * V​i​e​w​ ​i​m​a​g​e
	 */
	viewImage: string
	/**
	 * O​p​e​n​ ​o​r​i​g​i​n​a​l
	 */
	openOriginal: string
	/**
	 * F​i​l​e​ ​a​t​t​a​c​h​m​e​n​t
	 */
	fileAttachment: string
	/**
	 * D​e​c​r​y​p​t​i​n​g​ ​a​t​t​a​c​h​m​e​n​t
	 */
	decryptingAttachment: string
	/**
	 * C​o​u​l​d​ ​n​o​t​ ​d​e​c​r​y​p​t
	 */
	attachmentDecryptFailed: string
	/**
	 * U​p​l​o​a​d​ ​f​a​i​l​e​d
	 */
	uploadFailed: string
	/**
	 * E​n​c​r​y​p​t​i​o​n​ ​f​a​i​l​e​d​ ​-​ ​m​e​s​s​a​g​e​ ​n​o​t​ ​s​e​n​t
	 */
	encryptFailed: string
	/**
	 * D​i​s​m​i​s​s​ ​m​e​s​s​a​g​e
	 */
	dismissMessage: string
	/**
	 * S​i​g​n​e​d
	 */
	signed: string
	/**
	 * V​e​r​i​f​i​e​d​ ​s​e​n​d​e​r
	 */
	verified: string
	/**
	 * C​a​n​c​e​l
	 */
	cancelEdit: string
	/**
	 * Y​o​u
	 */
	you: string
	/**
	 * P​r​i​v​a​c​y
	 */
	privacy: string
	/**
	 * S​e​n​d​ ​t​y​p​i​n​g​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
	 */
	sendTyping: string
	/**
	 * S​e​n​d​ ​d​e​l​i​v​e​r​y​ ​r​e​c​e​i​p​t​s
	 */
	sendReceipts: string
	/**
	 * S​e​n​d​ ​r​e​a​d​ ​m​a​r​k​e​r​s
	 */
	sendReadMarkers: string
	/**
	 * S​h​a​r​e​ ​c​r​a​s​h​ ​r​e​p​o​r​t​s
	 */
	crashReporting: string
	/**
	 * S​e​n​d​s​ ​a​ ​s​c​r​u​b​b​e​d​ ​e​r​r​o​r​ ​r​e​p​o​r​t​ ​w​h​e​n​ ​s​o​m​e​t​h​i​n​g​ ​b​r​e​a​k​s​.​ ​A​d​d​r​e​s​s​e​s​ ​a​r​e​ ​r​e​m​o​v​e​d​ ​b​e​f​o​r​e​ ​s​e​n​d​i​n​g​,​ ​a​n​d​ ​r​e​p​o​r​t​i​n​g​ ​o​n​l​y​ ​w​o​r​k​s​ ​i​f​ ​t​h​i​s​ ​d​e​p​l​o​y​m​e​n​t​ ​c​o​n​f​i​g​u​r​e​d​ ​a​ ​s​e​r​v​e​r​.
	 */
	crashReportingHint: string
	/**
	 * S​p​l​i​t​ ​v​i​e​w
	 */
	splitView: string
	/**
	 * C​l​o​s​e​ ​p​a​n​e
	 */
	closePane: string
	/**
	 * O​p​e​n​ ​i​n​ ​s​p​l​i​t​ ​v​i​e​w
	 */
	openInSplit: string
	/**
	 * C​h​o​o​s​e​ ​a​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	pickConversation: string
	/**
	 * P​l​a​y
	 */
	play: string
	/**
	 * P​a​u​s​e
	 */
	pause: string
	/**
	 * P​i​c​k​ ​a​n​ ​e​m​o​j​i
	 */
	addReactionEmoji: string
	/**
	 * M​e​s​s​a​g​e​ ​s​i​g​n​e​d
	 */
	messageSigned: string
	/**
	 * L​o​a​d​ ​o​l​d​e​r​ ​m​e​s​s​a​g​e​s
	 */
	loadOlder: string
	/**
	 * B​e​g​i​n​n​i​n​g​ ​o​f​ ​t​h​e​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	beginningOfHistory: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settings: string
	/**
	 * P​r​e​f​e​r​e​n​c​e​s​ ​a​r​e​ ​s​t​o​r​e​d​ ​o​n​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​o​n​l​y
	 */
	settingsHint: string
	/**
	 * S​e​a​r​c​h​ ​s​e​t​t​i​n​g​s
	 */
	searchSettings: string
	/**
	 * A​p​p​e​a​r​a​n​c​e
	 */
	appearance: string
	/**
	 * T​h​e​m​e
	 */
	theme: string
	/**
	 * L​i​g​h​t
	 */
	themeLight: string
	/**
	 * D​a​r​k
	 */
	themeDark: string
	/**
	 * S​y​s​t​e​m
	 */
	themeSystem: string
	/**
	 * A​c​c​e​n​t​ ​c​o​l​o​r
	 */
	accentColor: string
	/**
	 * C​u​s​t​o​m​ ​h​u​e
	 */
	accentHue: string
	/**
	 * A​c​c​o​u​n​t​s
	 */
	accounts: string
	/**
	 * G​e​n​e​r​a​l
	 */
	general: string
	/**
	 * S​e​n​d​ ​m​e​s​s​a​g​e​s​ ​w​i​t​h​ ​E​n​t​e​r
	 */
	sendWithEnter: string
	/**
	 * D​e​s​k​t​o​p​ ​n​o​t​i​f​i​c​a​t​i​o​n​s
	 */
	notifications: string
	/**
	 * N​o​t​i​f​i​c​a​t​i​o​n​ ​s​o​u​n​d​s
	 */
	sounds: string
	/**
	 * K​e​y​b​o​a​r​d​ ​s​h​o​r​t​c​u​t​s
	 */
	keyboard: string
	/**
	 * C​l​i​c​k​ ​a​ ​s​h​o​r​t​c​u​t​ ​t​o​ ​r​e​b​i​n​d​ ​i​t​.​ ​P​r​e​s​s​ ​E​s​c​a​p​e​ ​t​o​ ​c​a​n​c​e​l​.
	 */
	keyboardHint: string
	/**
	 * p​r​e​s​s​ ​k​e​y​s
	 */
	pressKeys: string
	/**
	 * R​e​b​i​n​d​ ​{​a​c​t​i​o​n​}
	 * @param {string} action
	 */
	rebindFor: RequiredParams<'action'>
	/**
	 * R​e​s​e​t​ ​t​o​ ​d​e​f​a​u​l​t
	 */
	resetBinding: string
	/**
	 * O​p​e​n​ ​s​e​t​t​i​n​g​s
	 */
	kbSettings: string
	/**
	 * T​o​g​g​l​e​ ​t​h​e​m​e
	 */
	kbToggleTheme: string
	/**
	 * N​e​x​t​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	kbNextConversation: string
	/**
	 * P​r​e​v​i​o​u​s​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	kbPrevConversation: string
	/**
	 * C​l​o​s​e​ ​c​o​n​v​e​r​s​a​t​i​o​n
	 */
	kbCloseConversation: string
	/**
	 * F​o​c​u​s​ ​m​e​s​s​a​g​e​ ​i​n​p​u​t
	 */
	kbFocusComposer: string
	/**
	 * T​o​g​g​l​e​ ​s​i​d​e​b​a​r
	 */
	kbToggleSidebar: string
	/**
	 * O​p​e​n​ ​c​o​m​m​a​n​d​ ​p​a​l​e​t​t​e
	 */
	kbCommandPalette: string
	/**
	 * S​w​i​t​c​h​ ​t​o​ ​a​c​c​o​u​n​t​ ​{​n​}
	 * @param {number} n
	 */
	kbAccount: RequiredParams<'n'>
	/**
	 * S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g
	 */
	crashTitle: string
	/**
	 * T​h​e​ ​a​p​p​ ​h​i​t​ ​a​n​ ​u​n​e​x​p​e​c​t​e​d​ ​e​r​r​o​r​.​ ​Y​o​u​r​ ​m​e​s​s​a​g​e​s​ ​a​r​e​ ​s​t​o​r​e​d​ ​l​o​c​a​l​l​y​ ​a​n​d​ ​n​o​t​h​i​n​g​ ​w​a​s​ ​s​e​n​t​ ​a​n​y​w​h​e​r​e​.
	 */
	crashDescription: string
	/**
	 * T​r​y​ ​a​g​a​i​n
	 */
	crashRetry: string
	/**
	 * R​e​l​o​a​d​ ​a​p​p
	 */
	crashReload: string
	/**
	 * C​o​p​y​ ​e​r​r​o​r
	 */
	copyError: string
	/**
	 * C​o​p​i​e​d
	 */
	copied: string
	/**
	 * C​o​n​n​e​c​t​e​d​ ​a​s​ ​{​j​i​d​}
	 * @param {string} jid
	 */
	toastConnected: RequiredParams<'jid'>
	/**
	 * C​o​n​n​e​c​t​i​o​n​ ​p​r​o​b​l​e​m​ ​f​o​r​ ​{​j​i​d​}
	 * @param {string} jid
	 */
	toastConnectionError: RequiredParams<'jid'>
	/**
	 * D​i​s​c​o​n​n​e​c​t​e​d​:​ ​{​j​i​d​}
	 * @param {string} jid
	 */
	toastDisconnected: RequiredParams<'jid'>
	/**
	 * R​e​m​o​v​e​ ​t​h​i​s​ ​a​c​c​o​u​n​t​?
	 */
	removeAccountTitle: string
	/**
	 * {​j​i​d​}​ ​w​i​l​l​ ​b​e​ ​d​i​s​c​o​n​n​e​c​t​e​d​ ​a​n​d​ ​i​t​s​ ​l​o​c​a​l​ ​d​a​t​a​ ​o​n​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​d​e​l​e​t​e​d​.​ ​T​h​e​ ​a​c​c​o​u​n​t​ ​i​t​s​e​l​f​ ​s​t​a​y​s​ ​o​n​ ​t​h​e​ ​s​e​r​v​e​r​.
	 * @param {string} jid
	 */
	removeAccountDescription: RequiredParams<'jid'>
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * R​e​m​o​v​e
	 */
	confirm: string
	/**
	 * m​o​d
	 */
	roleModerator: string
	/**
	 * a​d​m​i​n
	 */
	roleAdmin: string
	/**
	 * O​p​e​n​ ​s​e​t​t​i​n​g​s
	 */
	openSettings: string
	/**
	 * L​o​a​d​i​n​g​ ​c​o​n​t​a​c​t​s
	 */
	loadingContacts: string
	/**
	 * C​o​n​n​e​c​t​i​n​g​ ​t​o​ ​t​h​e​ ​s​e​r​v​e​r
	 */
	connectingStatus: string
	/**
	 * C​o​l​l​a​p​s​e​ ​s​i​d​e​b​a​r
	 */
	collapseSidebar: string
	/**
	 * E​x​p​a​n​d​ ​s​i​d​e​b​a​r
	 */
	expandSidebar: string
	/**
	 * S​e​t​ ​y​o​u​r​ ​p​r​e​s​e​n​c​e
	 */
	presencePickerLabel: string
	/**
	 * S​t​a​t​u​s​ ​m​e​s​s​a​g​e
	 */
	statusMessage: string
	/**
	 * S​e​t​ ​a​ ​s​t​a​t​u​s​ ​m​e​s​s​a​g​e
	 */
	statusPlaceholder: string
	/**
	 * P​r​e​s​s​ ​E​n​t​e​r​ ​t​o​ ​a​p​p​l​y
	 */
	statusMessageHint: string
	/**
	 * C​h​a​t​ ​o​p​t​i​o​n​s
	 */
	chatOptions: string
	/**
	 * B​l​o​c​k
	 */
	block: string
	/**
	 * U​n​b​l​o​c​k
	 */
	unblock: string
	/**
	 * B​l​o​c​k​ ​u​s​e​r
	 */
	blockUser: string
	/**
	 * U​n​b​l​o​c​k​ ​u​s​e​r
	 */
	unblockUser: string
	/**
	 * B​l​o​c​k​ ​t​h​i​s​ ​c​o​n​t​a​c​t​?
	 */
	blockUserTitle: string
	/**
	 * {​j​i​d​}​ ​w​i​l​l​ ​n​o​ ​l​o​n​g​e​r​ ​b​e​ ​a​b​l​e​ ​t​o​ ​s​e​n​d​ ​y​o​u​ ​m​e​s​s​a​g​e​s​ ​o​r​ ​s​e​e​ ​y​o​u​r​ ​p​r​e​s​e​n​c​e​.
	 * @param {string} jid
	 */
	blockUserDescription: RequiredParams<'jid'>
	/**
	 * B​l​o​c​k​e​d​ ​c​o​n​t​a​c​t​s
	 */
	blockedContacts: string
	/**
	 * B​l​o​c​k​ ​a​n​ ​a​d​d​r​e​s​s​,​ ​e​.​g​.​ ​s​p​a​m​@​e​x​a​m​p​l​e​.​o​r​g
	 */
	blockJidPlaceholder: string
	/**
	 * U​n​b​l​o​c​k​ ​{​j​i​d​}
	 * @param {string} jid
	 */
	unblockJid: RequiredParams<'jid'>
	/**
	 * U​n​b​l​o​c​k​ ​a​l​l
	 */
	unblockAll: string
	/**
	 * N​o​b​o​d​y​ ​i​s​ ​b​l​o​c​k​e​d
	 */
	blockedEmpty: string
	/**
	 * N​o​ ​b​l​o​c​k​e​d​ ​c​o​n​t​a​c​t​s​ ​m​a​t​c​h​ ​t​h​e​ ​s​e​a​r​c​h
	 */
	noBlockedMatch: string
	/**
	 * b​l​o​c​k​e​d
	 */
	blockedBadge: string
	/**
	 * S​e​a​r​c​h​ ​m​e​m​b​e​r​s
	 */
	searchMembers: string
	/**
	 * N​o​ ​m​e​m​b​e​r​s​ ​m​a​t​c​h​ ​t​h​e​ ​s​e​a​r​c​h
	 */
	noMembersFound: string
	/**
	 * M​o​d​e​r​a​t​o​r​s
	 */
	groupModerators: string
	/**
	 * M​e​m​b​e​r​s
	 */
	groupParticipants: string
	/**
	 * V​i​s​i​t​o​r​s
	 */
	groupVisitors: string
	/**
	 * E​n​c​r​y​p​t​i​o​n
	 */
	encryption: string
	/**
	 * Y​o​u​r​ ​d​e​v​i​c​e​ ​f​i​n​g​e​r​p​r​i​n​t
	 */
	yourDevice: string
	/**
	 * C​o​p​y​ ​f​i​n​g​e​r​p​r​i​n​t
	 */
	copyFingerprint: string
	/**
	 * F​i​n​g​e​r​p​r​i​n​t
	 */
	fingerprint: string
	/**
	 * D​e​v​i​c​e​ ​{​i​d​}
	 * @param {number} id
	 */
	deviceId: RequiredParams<'id'>
	/**
	 * N​o​ ​O​M​E​M​O​ ​d​e​v​i​c​e​s​ ​p​u​b​l​i​s​h​e​d
	 */
	noOmemoDevices: string
	/**
	 * O​M​E​M​O​ ​i​s​ ​n​o​t​ ​a​v​a​i​l​a​b​l​e​ ​f​o​r​ ​t​h​i​s​ ​a​c​c​o​u​n​t​ ​y​e​t
	 */
	omemoUnavailable: string
	/**
	 * T​h​i​s​ ​d​e​v​i​c​e​ ​c​a​n​n​o​t​ ​s​t​o​r​e​ ​e​n​c​r​y​p​t​i​o​n​ ​k​e​y​s​ ​s​e​c​u​r​e​l​y​.​ ​K​e​y​s​ ​a​r​e​ ​k​e​p​t​ ​i​n​ ​p​l​a​i​n​ ​b​r​o​w​s​e​r​ ​s​t​o​r​a​g​e​.
	 */
	omemoInsecureStorage: string
	/**
	 * B​l​i​n​d​l​y​ ​t​r​u​s​t​ ​n​e​w​ ​d​e​v​i​c​e​s
	 */
	omemoBlindTrust: string
	/**
	 * T​r​u​s​t​ ​o​n​ ​f​i​r​s​t​ ​u​s​e​:​ ​n​e​w​ ​d​e​v​i​c​e​ ​f​i​n​g​e​r​p​r​i​n​t​s​ ​a​r​e​ ​t​r​u​s​t​e​d​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​.​ ​Y​o​u​ ​c​a​n​ ​s​t​i​l​l​ ​v​e​r​i​f​y​ ​o​r​ ​d​i​s​t​r​u​s​t​ ​t​h​e​m​ ​b​e​l​o​w​.
	 */
	omemoBlindTrustHint: string
	/**
	 * V​e​r​i​f​i​e​d
	 */
	trustVerified: string
	/**
	 * B​l​i​n​d​l​y​ ​t​r​u​s​t​e​d
	 */
	trustBlind: string
	/**
	 * N​o​t​ ​v​e​r​i​f​i​e​d
	 */
	trustUndecided: string
	/**
	 * D​i​s​t​r​u​s​t​e​d
	 */
	trustDistrusted: string
	/**
	 * T​h​i​s​ ​d​e​v​i​c​e​ ​p​r​e​s​e​n​t​e​d​ ​a​ ​n​e​w​ ​k​e​y​ ​s​i​n​c​e​ ​y​o​u​ ​l​a​s​t​ ​s​a​w​ ​i​t
	 */
	keyChanged: string
	/**
	 * V​e​r​i​f​y
	 */
	verify: string
	/**
	 * V​e​r​i​f​y​ ​t​h​i​s​ ​d​e​v​i​c​e​?
	 */
	verifyFingerprintTitle: string
	/**
	 * C​o​m​p​a​r​e​ ​t​h​i​s​ ​f​i​n​g​e​r​p​r​i​n​t​ ​w​i​t​h​ ​{​j​i​d​}​ ​t​h​r​o​u​g​h​ ​a​n​o​t​h​e​r​ ​c​h​a​n​n​e​l​ ​b​e​f​o​r​e​ ​c​o​n​f​i​r​m​i​n​g​.
	 * @param {string} jid
	 */
	verifyFingerprintDescription: RequiredParams<'jid'>
	/**
	 * D​i​s​t​r​u​s​t
	 */
	distrust: string
	/**
	 * D​i​s​t​r​u​s​t​ ​t​h​i​s​ ​d​e​v​i​c​e​?
	 */
	distrustTitle: string
	/**
	 * {​j​i​d​}​ ​w​i​l​l​ ​s​t​o​p​ ​r​e​c​e​i​v​i​n​g​ ​e​n​c​r​y​p​t​e​d​ ​c​o​p​i​e​s​ ​o​f​ ​y​o​u​r​ ​m​e​s​s​a​g​e​s​ ​o​n​ ​t​h​i​s​ ​d​e​v​i​c​e​.
	 * @param {string} jid
	 */
	distrustDescription: RequiredParams<'jid'>
	/**
	 * T​r​u​s​t​ ​a​g​a​i​n
	 */
	trustAgain: string
	/**
	 * E​n​c​r​y​p​t​e​d​ ​m​e​s​s​a​g​e​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​d​e​c​r​y​p​t​e​d
	 */
	couldNotDecrypt: string
	/**
	 * A​s​k​e​d​ ​t​h​e​ ​s​e​n​d​e​r​ ​t​o​ ​r​e​p​a​i​r​ ​t​h​e​ ​e​n​c​r​y​p​t​i​o​n​ ​s​e​s​s​i​o​n
	 */
	keyRequested: string
	/**
	 * F​r​o​m​ ​a​n​ ​u​n​v​e​r​i​f​i​e​d​ ​d​e​v​i​c​e
	 */
	untrustedDevice: string
	/**
	 * E​n​d​-​t​o​-​e​n​d​ ​e​n​c​r​y​p​t​e​d
	 */
	encryptedChat: string
	/**
	 * L​o​a​d​i​n​g
	 */
	loading: string
	/**
	 * C​l​o​s​e
	 */
	close: string
	/**
	 * R​e​c​o​r​d​i​n​g
	 */
	recording: string
	/**
	 * D​a​n​g​e​r​ ​z​o​n​e
	 */
	dangerZone: string
	/**
	 * W​i​p​e​ ​l​o​c​a​l​ ​d​a​t​a
	 */
	wipeData: string
	/**
	 * D​e​l​e​t​e​ ​a​l​l​ ​l​o​c​a​l​ ​m​e​s​s​a​g​e​s​,​ ​k​e​y​s​ ​a​n​d​ ​s​e​t​t​i​n​g​s​ ​o​n​ ​t​h​i​s​ ​d​e​v​i​c​e
	 */
	wipeDataHint: string
	/**
	 * W​i​p​e​ ​a​l​l​ ​l​o​c​a​l​ ​d​a​t​a​?
	 */
	wipeDataTitle: string
	/**
	 * E​v​e​r​y​ ​a​c​c​o​u​n​t​ ​s​e​s​s​i​o​n​,​ ​c​a​c​h​e​d​ ​m​e​s​s​a​g​e​ ​a​n​d​ ​s​t​o​r​e​d​ ​k​e​y​ ​o​n​ ​t​h​i​s​ ​d​e​v​i​c​e​ ​w​i​l​l​ ​b​e​ ​d​e​l​e​t​e​d​.​ ​T​h​i​s​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
	 */
	wipeDataDescription: string
}

export type TranslationFunctions = {
	/**
	 * Badinage
	 */
	appName: () => LocalizedString
	/**
	 * bad-in-AHZH, playful banter
	 */
	appPronunciation: () => LocalizedString
	/**
	 * Sign in
	 */
	signIn: () => LocalizedString
	/**
	 * Sign in to your XMPP account
	 */
	signInTitle: () => LocalizedString
	/**
	 * XMPP address
	 */
	jid: () => LocalizedString
	/**
	 * you@example.org
	 */
	jidPlaceholder: () => LocalizedString
	/**
	 * Password
	 */
	password: () => LocalizedString
	/**
	 * Server
	 */
	server: () => LocalizedString
	/**
	 * wss://example.org/xmpp-websocket
	 */
	serverPlaceholder: () => LocalizedString
	/**
	 * Leave empty to discover the server automatically
	 */
	serverHint: () => LocalizedString
	/**
	 * Keep me signed in until I close this tab
	 */
	rememberSession: () => LocalizedString
	/**
	 * Connect
	 */
	connect: () => LocalizedString
	/**
	 * Connecting
	 */
	connecting: () => LocalizedString
	/**
	 * Authentication failed
	 */
	authFailed: () => LocalizedString
	/**
	 * Could not reach the server
	 */
	connectionError: () => LocalizedString
	/**
	 * Conversations
	 */
	conversations: () => LocalizedString
	/**
	 * Contacts
	 */
	contacts: () => LocalizedString
	/**
	 * Add account
	 */
	addAccount: () => LocalizedString
	/**
	 * Remove account
	 */
	removeAccount: () => LocalizedString
	/**
	 * online
	 */
	online: () => LocalizedString
	/**
	 * offline
	 */
	offline: () => LocalizedString
	/**
	 * away
	 */
	away: () => LocalizedString
	/**
	 * busy
	 */
	busy: () => LocalizedString
	/**
	 * extended away
	 */
	extendedAway: () => LocalizedString
	/**
	 * Message {peer}
	 */
	messagePlaceholder: (arg: { peer: string }) => LocalizedString
	/**
	 * Send
	 */
	send: () => LocalizedString
	/**
	 * Select a conversation or contact to start chatting
	 */
	noConversation: () => LocalizedString
	/**
	 * No contacts yet
	 */
	emptyRoster: () => LocalizedString
	/**
	 * Toggle theme
	 */
	toggleTheme: () => LocalizedString
	/**
	 * Back
	 */
	back: () => LocalizedString
	/**
	 * Encrypted
	 */
	encrypted: () => LocalizedString
	/**
	 * Not encrypted
	 */
	notEncrypted: () => LocalizedString
	/**
	 * {count} unread
	 */
	unread: (arg: { count: number }) => LocalizedString
	/**
	 * typing…
	 */
	typing: () => LocalizedString
	/**
	 * {name} is typing…
	 */
	typingNick: (arg: { name: string }) => LocalizedString
	/**
	 * {names} typing…
	 */
	typingNames: (arg: { names: string }) => LocalizedString
	/**
	 * Seen
	 */
	seen: () => LocalizedString
	/**
	 * Try the demo
	 */
	tryDemo: () => LocalizedString
	/**
	 * No server needed. Fake contacts, fake chats, all local.
	 */
	demoHint: () => LocalizedString
	/**
	 * Demo
	 */
	demoBadge: () => LocalizedString
	/**
	 * Rooms
	 */
	rooms: () => LocalizedString
	/**
	 * Join a room
	 */
	joinRoom: () => LocalizedString
	/**
	 * Room address
	 */
	roomJid: () => LocalizedString
	/**
	 * room@conference.example.org
	 */
	roomJidPlaceholder: () => LocalizedString
	/**
	 * Nickname
	 */
	nickname: () => LocalizedString
	/**
	 * your nickname in the room
	 */
	nicknamePlaceholder: () => LocalizedString
	/**
	 * Join
	 */
	join: () => LocalizedString
	/**
	 * Leave room
	 */
	leaveRoom: () => LocalizedString
	/**
	 * {count} occupants
	 */
	occupants: (arg: { count: number }) => LocalizedString
	/**
	 * Room subject
	 */
	roomSubject: () => LocalizedString
	/**
	 * Add a contact
	 */
	addContact: () => LocalizedString
	/**
	 * Contact address
	 */
	contactJid: () => LocalizedString
	/**
	 * Display name
	 */
	contactName: () => LocalizedString
	/**
	 * Add
	 */
	add: () => LocalizedString
	/**
	 * Subscription requests
	 */
	subscriptionRequests: () => LocalizedString
	/**
	 * {from} wants to see your presence
	 */
	wantsToSubscribe: (arg: { from: string }) => LocalizedString
	/**
	 * Accept
	 */
	accept: () => LocalizedString
	/**
	 * Deny
	 */
	deny: () => LocalizedString
	/**
	 * Delivered
	 */
	delivered: () => LocalizedString
	/**
	 * Read
	 */
	read: () => LocalizedString
	/**
	 * Sent
	 */
	sent: () => LocalizedString
	/**
	 * Search conversations and contacts
	 */
	search: () => LocalizedString
	/**
	 * Search conversations, contacts, actions
	 */
	palettePlaceholder: () => LocalizedString
	/**
	 * Actions
	 */
	paletteActions: () => LocalizedString
	/**
	 * No results
	 */
	paletteEmpty: () => LocalizedString
	/**
	 * No settings match your search
	 */
	noSettingsResults: () => LocalizedString
	/**
	 * Expand section
	 */
	expandSection: () => LocalizedString
	/**
	 * Collapse section
	 */
	collapseSection: () => LocalizedString
	/**
	 * Reply
	 */
	reply: () => LocalizedString
	/**
	 * Replying to {name}
	 */
	replyingTo: (arg: { name: string }) => LocalizedString
	/**
	 * Edit message
	 */
	editMessage: () => LocalizedString
	/**
	 * Editing message
	 */
	editingMessage: () => LocalizedString
	/**
	 * edited
	 */
	edited: () => LocalizedString
	/**
	 * Add reaction
	 */
	react: () => LocalizedString
	/**
	 * Copy message text
	 */
	copyMessage: () => LocalizedString
	/**
	 * Attach file
	 */
	attachFile: () => LocalizedString
	/**
	 * Drop files to send
	 */
	dropToSend: () => LocalizedString
	/**
	 * Search emoji
	 */
	searchEmoji: () => LocalizedString
	/**
	 * Record voice message
	 */
	recordVoice: () => LocalizedString
	/**
	 * Stop and send
	 */
	stopRecording: () => LocalizedString
	/**
	 * Cancel recording
	 */
	cancelRecording: () => LocalizedString
	/**
	 * Voice message
	 */
	voiceMessage: () => LocalizedString
	/**
	 * Image attachment
	 */
	imageAttachment: () => LocalizedString
	/**
	 * Video attachment
	 */
	videoAttachment: () => LocalizedString
	/**
	 * Seek
	 */
	videoSeek: () => LocalizedString
	/**
	 * Mute
	 */
	mute: () => LocalizedString
	/**
	 * Unmute
	 */
	unmute: () => LocalizedString
	/**
	 * Fullscreen
	 */
	fullscreen: () => LocalizedString
	/**
	 * View image
	 */
	viewImage: () => LocalizedString
	/**
	 * Open original
	 */
	openOriginal: () => LocalizedString
	/**
	 * File attachment
	 */
	fileAttachment: () => LocalizedString
	/**
	 * Decrypting attachment
	 */
	decryptingAttachment: () => LocalizedString
	/**
	 * Could not decrypt
	 */
	attachmentDecryptFailed: () => LocalizedString
	/**
	 * Upload failed
	 */
	uploadFailed: () => LocalizedString
	/**
	 * Encryption failed - message not sent
	 */
	encryptFailed: () => LocalizedString
	/**
	 * Dismiss message
	 */
	dismissMessage: () => LocalizedString
	/**
	 * Signed
	 */
	signed: () => LocalizedString
	/**
	 * Verified sender
	 */
	verified: () => LocalizedString
	/**
	 * Cancel
	 */
	cancelEdit: () => LocalizedString
	/**
	 * You
	 */
	you: () => LocalizedString
	/**
	 * Privacy
	 */
	privacy: () => LocalizedString
	/**
	 * Send typing notifications
	 */
	sendTyping: () => LocalizedString
	/**
	 * Send delivery receipts
	 */
	sendReceipts: () => LocalizedString
	/**
	 * Send read markers
	 */
	sendReadMarkers: () => LocalizedString
	/**
	 * Share crash reports
	 */
	crashReporting: () => LocalizedString
	/**
	 * Sends a scrubbed error report when something breaks. Addresses are removed before sending, and reporting only works if this deployment configured a server.
	 */
	crashReportingHint: () => LocalizedString
	/**
	 * Split view
	 */
	splitView: () => LocalizedString
	/**
	 * Close pane
	 */
	closePane: () => LocalizedString
	/**
	 * Open in split view
	 */
	openInSplit: () => LocalizedString
	/**
	 * Choose a conversation
	 */
	pickConversation: () => LocalizedString
	/**
	 * Play
	 */
	play: () => LocalizedString
	/**
	 * Pause
	 */
	pause: () => LocalizedString
	/**
	 * Pick an emoji
	 */
	addReactionEmoji: () => LocalizedString
	/**
	 * Message signed
	 */
	messageSigned: () => LocalizedString
	/**
	 * Load older messages
	 */
	loadOlder: () => LocalizedString
	/**
	 * Beginning of the conversation
	 */
	beginningOfHistory: () => LocalizedString
	/**
	 * Settings
	 */
	settings: () => LocalizedString
	/**
	 * Preferences are stored on this device only
	 */
	settingsHint: () => LocalizedString
	/**
	 * Search settings
	 */
	searchSettings: () => LocalizedString
	/**
	 * Appearance
	 */
	appearance: () => LocalizedString
	/**
	 * Theme
	 */
	theme: () => LocalizedString
	/**
	 * Light
	 */
	themeLight: () => LocalizedString
	/**
	 * Dark
	 */
	themeDark: () => LocalizedString
	/**
	 * System
	 */
	themeSystem: () => LocalizedString
	/**
	 * Accent color
	 */
	accentColor: () => LocalizedString
	/**
	 * Custom hue
	 */
	accentHue: () => LocalizedString
	/**
	 * Accounts
	 */
	accounts: () => LocalizedString
	/**
	 * General
	 */
	general: () => LocalizedString
	/**
	 * Send messages with Enter
	 */
	sendWithEnter: () => LocalizedString
	/**
	 * Desktop notifications
	 */
	notifications: () => LocalizedString
	/**
	 * Notification sounds
	 */
	sounds: () => LocalizedString
	/**
	 * Keyboard shortcuts
	 */
	keyboard: () => LocalizedString
	/**
	 * Click a shortcut to rebind it. Press Escape to cancel.
	 */
	keyboardHint: () => LocalizedString
	/**
	 * press keys
	 */
	pressKeys: () => LocalizedString
	/**
	 * Rebind {action}
	 */
	rebindFor: (arg: { action: string }) => LocalizedString
	/**
	 * Reset to default
	 */
	resetBinding: () => LocalizedString
	/**
	 * Open settings
	 */
	kbSettings: () => LocalizedString
	/**
	 * Toggle theme
	 */
	kbToggleTheme: () => LocalizedString
	/**
	 * Next conversation
	 */
	kbNextConversation: () => LocalizedString
	/**
	 * Previous conversation
	 */
	kbPrevConversation: () => LocalizedString
	/**
	 * Close conversation
	 */
	kbCloseConversation: () => LocalizedString
	/**
	 * Focus message input
	 */
	kbFocusComposer: () => LocalizedString
	/**
	 * Toggle sidebar
	 */
	kbToggleSidebar: () => LocalizedString
	/**
	 * Open command palette
	 */
	kbCommandPalette: () => LocalizedString
	/**
	 * Switch to account {n}
	 */
	kbAccount: (arg: { n: number }) => LocalizedString
	/**
	 * Something went wrong
	 */
	crashTitle: () => LocalizedString
	/**
	 * The app hit an unexpected error. Your messages are stored locally and nothing was sent anywhere.
	 */
	crashDescription: () => LocalizedString
	/**
	 * Try again
	 */
	crashRetry: () => LocalizedString
	/**
	 * Reload app
	 */
	crashReload: () => LocalizedString
	/**
	 * Copy error
	 */
	copyError: () => LocalizedString
	/**
	 * Copied
	 */
	copied: () => LocalizedString
	/**
	 * Connected as {jid}
	 */
	toastConnected: (arg: { jid: string }) => LocalizedString
	/**
	 * Connection problem for {jid}
	 */
	toastConnectionError: (arg: { jid: string }) => LocalizedString
	/**
	 * Disconnected: {jid}
	 */
	toastDisconnected: (arg: { jid: string }) => LocalizedString
	/**
	 * Remove this account?
	 */
	removeAccountTitle: () => LocalizedString
	/**
	 * {jid} will be disconnected and its local data on this device deleted. The account itself stays on the server.
	 */
	removeAccountDescription: (arg: { jid: string }) => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Remove
	 */
	confirm: () => LocalizedString
	/**
	 * mod
	 */
	roleModerator: () => LocalizedString
	/**
	 * admin
	 */
	roleAdmin: () => LocalizedString
	/**
	 * Open settings
	 */
	openSettings: () => LocalizedString
	/**
	 * Loading contacts
	 */
	loadingContacts: () => LocalizedString
	/**
	 * Connecting to the server
	 */
	connectingStatus: () => LocalizedString
	/**
	 * Collapse sidebar
	 */
	collapseSidebar: () => LocalizedString
	/**
	 * Expand sidebar
	 */
	expandSidebar: () => LocalizedString
	/**
	 * Set your presence
	 */
	presencePickerLabel: () => LocalizedString
	/**
	 * Status message
	 */
	statusMessage: () => LocalizedString
	/**
	 * Set a status message
	 */
	statusPlaceholder: () => LocalizedString
	/**
	 * Press Enter to apply
	 */
	statusMessageHint: () => LocalizedString
	/**
	 * Chat options
	 */
	chatOptions: () => LocalizedString
	/**
	 * Block
	 */
	block: () => LocalizedString
	/**
	 * Unblock
	 */
	unblock: () => LocalizedString
	/**
	 * Block user
	 */
	blockUser: () => LocalizedString
	/**
	 * Unblock user
	 */
	unblockUser: () => LocalizedString
	/**
	 * Block this contact?
	 */
	blockUserTitle: () => LocalizedString
	/**
	 * {jid} will no longer be able to send you messages or see your presence.
	 */
	blockUserDescription: (arg: { jid: string }) => LocalizedString
	/**
	 * Blocked contacts
	 */
	blockedContacts: () => LocalizedString
	/**
	 * Block an address, e.g. spam@example.org
	 */
	blockJidPlaceholder: () => LocalizedString
	/**
	 * Unblock {jid}
	 */
	unblockJid: (arg: { jid: string }) => LocalizedString
	/**
	 * Unblock all
	 */
	unblockAll: () => LocalizedString
	/**
	 * Nobody is blocked
	 */
	blockedEmpty: () => LocalizedString
	/**
	 * No blocked contacts match the search
	 */
	noBlockedMatch: () => LocalizedString
	/**
	 * blocked
	 */
	blockedBadge: () => LocalizedString
	/**
	 * Search members
	 */
	searchMembers: () => LocalizedString
	/**
	 * No members match the search
	 */
	noMembersFound: () => LocalizedString
	/**
	 * Moderators
	 */
	groupModerators: () => LocalizedString
	/**
	 * Members
	 */
	groupParticipants: () => LocalizedString
	/**
	 * Visitors
	 */
	groupVisitors: () => LocalizedString
	/**
	 * Encryption
	 */
	encryption: () => LocalizedString
	/**
	 * Your device fingerprint
	 */
	yourDevice: () => LocalizedString
	/**
	 * Copy fingerprint
	 */
	copyFingerprint: () => LocalizedString
	/**
	 * Fingerprint
	 */
	fingerprint: () => LocalizedString
	/**
	 * Device {id}
	 */
	deviceId: (arg: { id: number }) => LocalizedString
	/**
	 * No OMEMO devices published
	 */
	noOmemoDevices: () => LocalizedString
	/**
	 * OMEMO is not available for this account yet
	 */
	omemoUnavailable: () => LocalizedString
	/**
	 * This device cannot store encryption keys securely. Keys are kept in plain browser storage.
	 */
	omemoInsecureStorage: () => LocalizedString
	/**
	 * Blindly trust new devices
	 */
	omemoBlindTrust: () => LocalizedString
	/**
	 * Trust on first use: new device fingerprints are trusted automatically. You can still verify or distrust them below.
	 */
	omemoBlindTrustHint: () => LocalizedString
	/**
	 * Verified
	 */
	trustVerified: () => LocalizedString
	/**
	 * Blindly trusted
	 */
	trustBlind: () => LocalizedString
	/**
	 * Not verified
	 */
	trustUndecided: () => LocalizedString
	/**
	 * Distrusted
	 */
	trustDistrusted: () => LocalizedString
	/**
	 * This device presented a new key since you last saw it
	 */
	keyChanged: () => LocalizedString
	/**
	 * Verify
	 */
	verify: () => LocalizedString
	/**
	 * Verify this device?
	 */
	verifyFingerprintTitle: () => LocalizedString
	/**
	 * Compare this fingerprint with {jid} through another channel before confirming.
	 */
	verifyFingerprintDescription: (arg: { jid: string }) => LocalizedString
	/**
	 * Distrust
	 */
	distrust: () => LocalizedString
	/**
	 * Distrust this device?
	 */
	distrustTitle: () => LocalizedString
	/**
	 * {jid} will stop receiving encrypted copies of your messages on this device.
	 */
	distrustDescription: (arg: { jid: string }) => LocalizedString
	/**
	 * Trust again
	 */
	trustAgain: () => LocalizedString
	/**
	 * Encrypted message could not be decrypted
	 */
	couldNotDecrypt: () => LocalizedString
	/**
	 * Asked the sender to repair the encryption session
	 */
	keyRequested: () => LocalizedString
	/**
	 * From an unverified device
	 */
	untrustedDevice: () => LocalizedString
	/**
	 * End-to-end encrypted
	 */
	encryptedChat: () => LocalizedString
	/**
	 * Loading
	 */
	loading: () => LocalizedString
	/**
	 * Close
	 */
	close: () => LocalizedString
	/**
	 * Recording
	 */
	recording: () => LocalizedString
	/**
	 * Danger zone
	 */
	dangerZone: () => LocalizedString
	/**
	 * Wipe local data
	 */
	wipeData: () => LocalizedString
	/**
	 * Delete all local messages, keys and settings on this device
	 */
	wipeDataHint: () => LocalizedString
	/**
	 * Wipe all local data?
	 */
	wipeDataTitle: () => LocalizedString
	/**
	 * Every account session, cached message and stored key on this device will be deleted. This cannot be undone.
	 */
	wipeDataDescription: () => LocalizedString
}

export type Formatters = {}
